#define MC_CEFMSG_EXECUTE_SCRIPT "cefbrowser_request_execute_script"
#define MC_CEFMSG_CALL_SCRIPT "cefbrowser_request_call_script"
#define MC_CEFMSG_GET_SELECTED_TEXT "cefbrowser_request_get_seleted_text"
#define MC_CEFMSG_GET_TITLE "cefbrowser_request_get_title"
#define MC_CEFMSG_ENABLE_JS_HANDLER "cebrowser_request_enable_js_handler"

#define MC_CEFMSG_JS_HANDLER "cefbrowser_js_handler"

#define MC_CEFMSG_RESULT "cefbrowser_result"
