#!/bin/bash
# Build libcairo 1.18.4 as a static library for macOS ARM64 using meson.
#
# Cairo 1.18.x switched from autotools to meson and dropped the bundled
# pixman — pixman is now an external dependency.
#
# Prerequisites (install once):
#   brew install meson ninja pixman libpng pkg-config
#
# Usage (from repo root):
#   sh prebuilt/scripts/build-libcairo-mac-arm64.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CAIRO_SRC="${REPO_ROOT}/thirdparty/libcairo"
BUILD_DIR="${REPO_ROOT}/_cache/mac/cairo-build"
PREBUILT_LIB="${REPO_ROOT}/prebuilt/lib/mac"

echo "=== Checking prerequisites ==="
for tool in meson ninja pkg-config; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "ERROR: '$tool' not found. Run: brew install meson ninja pkg-config"
        exit 1
    fi
done
if ! brew --prefix pixman >/dev/null 2>&1; then
    echo "ERROR: pixman not found. Run: brew install pixman"
    exit 1
fi

PIXMAN_PKG="$(brew --prefix pixman)/lib/pkgconfig"
echo "Using pixman from: $(brew --prefix pixman)"

echo "=== Configuring cairo 1.18.4 ==="
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"

PKG_CONFIG_PATH="${PIXMAN_PKG}" \
meson setup "${BUILD_DIR}" "${CAIRO_SRC}" \
    --buildtype=release \
    --default-library=static \
    --wrap-mode=nofallback \
    -Dquartz=enabled \
    -Dpng=enabled \
    -Dfontconfig=disabled \
    -Dfreetype=disabled \
    -Dglib=disabled \
    -Dxlib=disabled \
    -Dxcb=disabled \
    -Dtee=disabled \
    -Dlzo=disabled \
    -Dspectre=disabled \
    -Dsymbol-lookup=disabled \
    -Dtests=disabled \
    -Dgtk_doc=false

echo "=== Building cairo ==="
PKG_CONFIG_PATH="${PIXMAN_PKG}" ninja -C "${BUILD_DIR}"

echo "=== Copying generated headers into thirdparty/libcairo/src ==="
# cairo-features.h is generated by meson — copy it so the compiler can find it
cp "${BUILD_DIR}/src/cairo-features.h" "${CAIRO_SRC}/src/cairo-features.h"

echo "=== Installing into prebuilt/lib/mac ==="
mkdir -p "${PREBUILT_LIB}"

# Find the cairo static library (meson puts it in src/ subdir)
LIBCAIRO=$(find "${BUILD_DIR}" -name "libcairo.a" | head -1)
if [ -z "${LIBCAIRO}" ]; then
    echo "ERROR: libcairo.a not found in build output"
    exit 1
fi

# Merge pixman into libcairo.a so downstream targets don't need to link
# pixman separately — cairo 1.18 dropped the bundled pixman and now needs
# it as an external library.
LIBPIXMAN="$(brew --prefix pixman)/lib/libpixman-1.a"
if [ ! -f "${LIBPIXMAN}" ]; then
    echo "ERROR: libpixman-1.a not found at ${LIBPIXMAN}"
    echo "  Run: brew install pixman"
    exit 1
fi

echo "Merging pixman into libcairo.a..."
MERGE_DIR="${BUILD_DIR}/merge_tmp"
rm -rf "${MERGE_DIR}"
mkdir -p "${MERGE_DIR}/cairo" "${MERGE_DIR}/pixman"

# Extract objects from both archives
(cd "${MERGE_DIR}/cairo"  && ar -x "${LIBCAIRO}")
(cd "${MERGE_DIR}/pixman" && ar -x "${LIBPIXMAN}")

# Create merged archive
ar -rcs "${PREBUILT_LIB}/libcairo.a" \
    "${MERGE_DIR}/cairo"/*.o \
    "${MERGE_DIR}/pixman"/*.o

rm -rf "${MERGE_DIR}"
echo "=== Done: prebuilt/lib/mac/libcairo.a updated to cairo 1.18.4 (with pixman merged) ==="
