#!/bin/bash
# Build libcairo 1.18.4 as a static library for macOS ARM64 using meson.
#
# Cairo 1.18.x switched from autotools to meson and dropped the bundled
# pixman — pixman is now an external dependency.
#
# Prerequisites (install once):
#   brew install meson ninja pixman pkg-config
#
# Build order: this script must run AFTER build-libz-mac-arm64.sh and
# build-mac-extras.sh.  cairo is configured to link the repo's own zlib
# (prebuilt/lib/mac/libz.a) and libpng (prebuilt/lib/mac/libpng.a) rather
# than the macOS SDK / Homebrew copies — see Makefile.Mac.
#
# Usage (from repo root):
#   sh prebuilt/scripts/build-libcairo-mac-arm64.sh

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
CAIRO_SRC="${REPO_ROOT}/thirdparty/libcairo"
BUILD_DIR="${REPO_ROOT}/_cache/mac/cairo-build"
PREBUILT_LIB="${REPO_ROOT}/prebuilt/lib/mac"

echo "=== Checking prerequisites ==="
for tool in meson ninja pkg-config; do
    if ! command -v "$tool" >/dev/null 2>&1; then
        echo "ERROR: '$tool' not found. Run: brew install meson ninja pkg-config"
        exit 1
    fi
done
if ! brew --prefix pixman >/dev/null 2>&1; then
    echo "ERROR: pixman not found. Run: brew install pixman"
    exit 1
fi

PIXMAN_PKG="$(brew --prefix pixman)/lib/pkgconfig"
echo "Using pixman from: $(brew --prefix pixman)"

echo "=== Configuring cairo 1.18.4 ==="
rm -rf "${BUILD_DIR}"
mkdir -p "${BUILD_DIR}"

# ---------------------------------------------------------------------------
# Make cairo link the repo's own zlib + libpng instead of the macOS SDK /
# Homebrew copies.  cairo 1.18 discovers both via pkg-config, so we generate
# minimal .pc files describing the in-repo headers and the static archives
# built earlier in the prebuilt-mac pass (build-libz-mac-arm64.sh and
# build-mac-extras.sh).  PKG_CONFIG_PATH is searched before the system path,
# so cairo picks up the vendored versions and the repo stays self-consistent.
# ---------------------------------------------------------------------------
LIBZ_A="${PREBUILT_LIB}/libz.a"
LIBPNG_A="${PREBUILT_LIB}/libpng.a"
for dep_a in "${LIBZ_A}" "${LIBPNG_A}"; do
    if [ ! -f "${dep_a}" ]; then
        echo "ERROR: required prebuilt library not found: ${dep_a}"
        echo "  build-libcairo-mac-arm64.sh must run AFTER build-libz-mac-arm64.sh"
        echo "  and build-mac-extras.sh.  Check the prebuilt-mac order in Makefile.Mac."
        exit 1
    fi
done

PKG_DIR="${REPO_ROOT}/_cache/mac/cairo-pkgconfig"
rm -rf "${PKG_DIR}"
mkdir -p "${PKG_DIR}"

LIBZ_VERSION="$(head -n1 "${REPO_ROOT}/prebuilt/versions/libz" | tr -d '[:space:]')"
LIBPNG_VERSION="$(head -n1 "${REPO_ROOT}/prebuilt/versions/libpng" | tr -d '[:space:]')"
echo "Pointing cairo at vendored zlib ${LIBZ_VERSION} + libpng ${LIBPNG_VERSION}"

cat > "${PKG_DIR}/zlib.pc" <<EOF
Name: zlib
Description: zlib (HyperXTalk vendored copy)
Version: ${LIBZ_VERSION}
Libs: -L${PREBUILT_LIB} -lz
Cflags: -I${REPO_ROOT}/thirdparty/libz/src -I${REPO_ROOT}/thirdparty/libz/include
EOF

cat > "${PKG_DIR}/libpng.pc" <<EOF
Name: libpng
Description: libpng (HyperXTalk vendored copy)
Version: ${LIBPNG_VERSION}
Requires.private: zlib
Libs: -L${PREBUILT_LIB} -lpng
Libs.private: -lm
Cflags: -I${REPO_ROOT}/thirdparty/libpng/include
EOF

PKG_CONFIG_PATH="${PKG_DIR}:${PIXMAN_PKG}" \
meson setup "${BUILD_DIR}" "${CAIRO_SRC}" \
    --buildtype=release \
    --default-library=static \
    --wrap-mode=nofallback \
    -Dquartz=enabled \
    -Dpng=enabled \
    -Dfontconfig=disabled \
    -Dfreetype=disabled \
    -Dglib=disabled \
    -Dxlib=disabled \
    -Dxcb=disabled \
    -Dtee=disabled \
    -Dlzo=disabled \
    -Dspectre=disabled \
    -Dsymbol-lookup=disabled \
    -Dtests=disabled \
    -Dgtk_doc=false

echo "=== Building cairo ==="
PKG_CONFIG_PATH="${PKG_DIR}:${PIXMAN_PKG}" ninja -C "${BUILD_DIR}"

echo "=== Copying generated headers into thirdparty/libcairo/src ==="
# cairo-features.h is generated by meson — copy it so the compiler can find it
cp "${BUILD_DIR}/src/cairo-features.h" "${CAIRO_SRC}/src/cairo-features.h"

echo "=== Installing into prebuilt/lib/mac ==="
mkdir -p "${PREBUILT_LIB}"

# Find the cairo static library (meson puts it in src/ subdir)
LIBCAIRO=$(find "${BUILD_DIR}" -name "libcairo.a" | head -1)
if [ -z "${LIBCAIRO}" ]; then
    echo "ERROR: libcairo.a not found in build output"
    exit 1
fi

# Merge pixman into libcairo.a so downstream targets don't need to link
# pixman separately — cairo 1.18 dropped the bundled pixman and now needs
# it as an external library.
LIBPIXMAN="$(brew --prefix pixman)/lib/libpixman-1.a"
if [ ! -f "${LIBPIXMAN}" ]; then
    echo "ERROR: libpixman-1.a not found at ${LIBPIXMAN}"
    echo "  Run: brew install pixman"
    exit 1
fi

echo "Merging pixman into libcairo.a..."
MERGE_DIR="${BUILD_DIR}/merge_tmp"
rm -rf "${MERGE_DIR}"
mkdir -p "${MERGE_DIR}/cairo" "${MERGE_DIR}/pixman"

# Extract objects from both archives
(cd "${MERGE_DIR}/cairo"  && ar -x "${LIBCAIRO}")
(cd "${MERGE_DIR}/pixman" && ar -x "${LIBPIXMAN}")

# Create merged archive
ar -rcs "${PREBUILT_LIB}/libcairo.a" \
    "${MERGE_DIR}/cairo"/*.o \
    "${MERGE_DIR}/pixman"/*.o

rm -rf "${MERGE_DIR}"
echo "=== Done: prebuilt/lib/mac/libcairo.a updated to cairo 1.18.4 (with pixman merged) ==="
