#ifndef __MC_EXECUTION_ERRORS__
#define __MC_EXECUTION_ERRORS__
enum Exec_errors
{
EE_UNDEFINED=0,
EE_NO_MEMORY, // "Handler: Running low on memory, script aborted"
EE_RECURSION_LIMIT, // "recursionLimit: Recursion limit reached"
EE_ABS_BADSOURCE, // "abs: error in source expression"
EE_ACCEPT_BADEXP, // "accept: bad expression"
EE_ACLIP_LOUDNESSNAN, // "aclip: playLoudness is not an integer"
EE_ACOS_BADSOURCE, // "acos: error in source expression"
EE_MATH_DOMAIN, // "numeric: domain error"
EE_ADD_BADARRAY, // "add: error in matrix operation"
EE_ADD_BADDEST, // "add: destination has a bad format (numeric?)"
EE_ADD_BADSOURCE, // "add: error in source expression"
EE_ADD_CANTSET, // "add: can't set destination"
EE_ADD_MISMATCH, // "add: can't add array to scalar"
EE_ALIASREFERENCE_BADSOURCE, // "aliasReference: error in file expression"
EE_AND_BADLEFT, // "Operators and: error in left operand"
EE_AND_BADRIGHT, // "Operators and: error in right operand"
EE_ANDBITS_BADLEFT, // "Operators bitAnd: error in left operand"
EE_ANDBITS_BADRIGHT, // "Operators bitAnd: error in right operand"
EE_ANNUITY_BADPERIODS, // "annuity: error in period expression"
EE_ANNUITY_BADRATE, // "annuity: error in rate expression"
EE_ANSWER_BADQUESTION, // "answer: error in question expression"
EE_ANSWER_BADRESPONSE, // "answer: error in response expression"
EE_ANSWER_BADTITLE, // "answer: error in title expression"
EE_ARRAYOP_BADEXP, // "split: error in expression"
EE_ARROWKEY_BADEXP, // "arrowKey: error in direction expression"
EE_ARROWKEY_NOTAKEY, // "arrowKey: not a direction"
EE_ASIN_BADSOURCE, // "asin: error in source expression"
EE_UNUSED_0027, // "UNUSED"
EE_ASK_BADQUESTION, // "ask: error in question expression"
EE_ASK_BADREPLY, // "ask: error in reply expression"
EE_ASK_BADTITLE, // "ask: error in title expression"
EE_ATAN2_BADS1, // "atan2: error in first expression"
EE_ATAN2_BADS2, // "atan2: error in second expression"
EE_UNUSED_0033, // "UNUSED"
EE_ATAN_BADSOURCE, // "atan: error in source expression"
EE_UNUSED_0035, // "UNUSED"
EE_AVERAGE_BADSOURCE, // "average: error in source expression"
EE_BASE64DECODE_BADSOURCE, // "base64Decode: error in source expression"
EE_BASE64ENCODE_BADSOURCE, // "base64Encode: error in source expression"
EE_BASECONVERT_BADDESTBASE, // "baseConvert: bad destination base"
EE_BASECONVERT_BADSOURCE, // "baseConvert: error in source expression"
EE_BASECONVERT_BADSOURCEBASE, // "baseConvert: bad source base"
EE_BASECONVERT_CANTCONVERT, // "baseConvert: can't convert this number"
EE_BASECONVERT_NOTBASE10, // "baseConvert: destination is not base 10"
EE_BEEP_BADEXP, // "beep: error in expression"
EE_BINARYD_BADDEST, // "binaryDecode: destination is not a variable"
EE_BINARYD_BADFORMAT, // "binaryDecode: invalid data for parameter"
EE_BINARYD_BADPARAM, // "binaryDecode: not enough parameters"
EE_BINARYD_BADSOURCE, // "binaryDecode: error in source expression"
EE_BINARYE_BADFORMAT, // "binaryEncode: invalid data for parameter"
EE_BINARYE_BADPARAM, // "binaryEncode: not enough parameters"
EE_BINARYE_BADSOURCE, // "binaryEncode: error in source expression"
EE_BUTTON_BADMODIFIER, // "Button: bad accelerator modifier"
EE_BUTTON_FAMILYNAN, // "Button: family is not an integer"
EE_BUTTON_MENUBUTTONNAN, // "Button: menuButton is not an integer"
EE_BUTTON_MENUHISTORYNAN, // "Button: menuHistory is not an integer"
EE_BUTTON_MENULINESNAN, // "Button: menuLines is not an integer"
EE_BUTTON_MNEMONICNAN, // "Button: mnemonic is not an integer"
EE_CANCEL_IDNAN, // "cancel: message id is not an integer"
EE_CHARTONUM_BADSOURCE, // "charToNum: error in source expression"
EE_CHOOSE_BADEXP, // "choose: error in expression"
EE_CHOOSE_BADTOOL, // "choose: not a tool"
EE_CHUNK_BADBACKGROUNDEXP, // "Chunk: error in background expression"
EE_CHUNK_BADCARDEXP, // "Chunk: error in card expression"
EE_CHUNK_BADCHARMARK, // "Chunk: error in character range"
EE_CHUNK_BADCONTAINER, // "Chunk: container is not a button or field"
EE_CHUNK_BADEXPRESSION, // "Chunk: error in chunk expression"
EE_CHUNK_BADITEMMARK, // "Chunk: error in item range"
EE_CHUNK_BADLINEMARK, // "Chunk: error in line range"
EE_CHUNK_BADOBJECTEXP, // "Chunk: error in object expression"
EE_CHUNK_BADRANGEEND, // "Chunk: error in range end expression"
EE_CHUNK_BADRANGESTART, // "Chunk: error in range start expression"
EE_CHUNK_BADSTACKEXP, // "Chunk: error in stack expression"
EE_CHUNK_BADTEXT, // "Chunk: error in text string"
EE_CHUNK_BADTOKENMARK, // "Chunk: can't separate tokens"
EE_CHUNK_BADWORDMARK, // "Chunk: can't separate words"
EE_CHUNK_CANTDELETEOBJECT, // "Chunk: can't delete object"
EE_CHUNK_CANTFINDOBJECT, // "Chunk: can't find object"
EE_CHUNK_CANTGETATTS, // "Chunk: can't get object attributes"
EE_CHUNK_CANTGETDEST, // "Chunk: can't get value of destination container"
EE_CHUNK_CANTGETNUMBER, // "Chunk: can't get number"
EE_CHUNK_CANTGETSOURCE, // "Chunk: can't get source string"
EE_CHUNK_CANTGETSUBSTRING, // "Chunk: can't get substring"
EE_CHUNK_CANTMARK, // "Chunk: can't find substring"
EE_CHUNK_CANTSETATTS, // "Chunk: can't set attributes"
EE_CHUNK_CANTSETDEST, // "Chunk: can't store to destination container"
EE_CHUNK_CANTSETN, // "Chunk: can't set as a number"
EE_CHUNK_NOBACKGROUND, // "Chunk: can't find background"
EE_CHUNK_NOCARD, // "Chunk: can't find card"
EE_CHUNK_NOOBJECT, // "Chunk: no such object"
EE_CHUNK_NOPROP, // "Chunk: can't set property"
EE_CHUNK_NOSTACK, // "Chunk: can't find stack"
EE_CHUNK_NOTARGET, // "Chunk: no target found"
EE_CHUNK_NOTOPEN, // "Chunk: can't select object that isn't open"
EE_CHUNK_OBJECTNOTCONTAINER, // "Chunk: source is not a container"
EE_CHUNK_SETCANTGETBOJECT, // "Chunk: can't find object to store into"
EE_CHUNK_SETCANTGETDEST, // "Chunk: can't get source from container"
EE_CHUNK_SETNOTACONTAINER, // "Chunk: destination is not a container"
EE_CLICK_ABORT, // "click: script aborted"
EE_CLICK_BADBUTTON, // "click: expression is not a button number"
EE_CLICK_BADLOCATION, // "click: error in point expression"
EE_CLICK_NAP, // "click: expression is not a point"
EE_CLICK_STACKNOTOPEN, // "click: stack is not open"
EE_CLONE_BADNAME, // "clone: error in name expression"
EE_CLONE_CANTCLONE, // "clone: can't clone this object"
EE_CLONE_LOCKED, // "clone: stack is locked"
EE_CLONE_NOTARGET, // "clone: can't find object to clone"
EE_CLOSE_BADNAME, // "close: error in name expression"
EE_CLOSE_NOOBJ, // "close: can't find stack"
EE_COLOR_BADSELECTEDCOLOR, // "color: error setting selectedColor"
EE_COMPACT_NOTARGET, // "compact: can't find stack to save"
EE_COMPACT_NOTASTACK, // "compact: object is not a stack"
EE_COMPOUND_BADPERIODS, // "compound: error in periods expression"
EE_COMPOUND_BADRATE, // "compound: error in rate expression"
EE_COMPRESS_BADSOURCE, // "compress: error in source expression"
EE_COMPRESS_ERROR, // "compress: error occurred during compression"
EE_CONCATSPACE_BADLEFT, // "Operators &&: error in left operand"
EE_CONCATSPACE_BADRIGHT, // "Operators &&: error in right operand"
EE_CONCAT_BADLEFT, // "Operators &: error in left operand"
EE_CONCAT_BADRIGHT, // "Operators &: error in right operand"
EE_CONTAINS_BADLEFT, // "Operators contains: error in left operand"
EE_CONTAINS_BADRIGHT, // "Operators contains: error in right operand"
EE_CONVERT_CANTGET, // "convert: can't read from container"
EE_CONVERT_CANTSET, // "convert: can't set container"
EE_CLIPBOARD_BADDEST, // "copy: invalid destination object"
EE_CLIPBOARD_NODEST, // "copy: can't find destination object"
EE_CLIPBOARD_BADOBJ, // "copy: can't copy source object"
EE_COPY_NOOBJ, // "copy: can't find source object"
EE_COPY_PASSWORD, // "copy: stack is password protected"
EE_COS_BADSOURCE, // "cos: error in source expression"
EE_UNUSED_0130, // "UNUSED"
EE_CREATE_BADBGORCARD, // "create: error in bad parent or background expression"
EE_CREATE_BADEXP, // "create: error in name expression"
EE_CREATE_BADFILEEXP, // "create: error in file name expression"
EE_CREATE_LOCKED, // "create: stack is locked (cantModify)"
EE_CROP_NOIMAGE, // "crop: error in image expression"
EE_CROP_NOTIMAGE, // "crop: object is not an image"
EE_CROP_CANTGETRECT, // "crop: error in rectangle expression"
EE_CROP_NAR, // "crop: expression is not a rectangle"
EE_CUT_NOOBJ, // "cut: can't find or copy object"
EE_DECOMPRESS_BADSOURCE, // "decompress: error in source expression"
EE_DECOMPRESS_NOTCOMPRESSED, // "decompress: string is not compressed data"
EE_DECOMPRESS_ERROR, // "decompress: error during decompression"
EE_DELETE_BADFILEEXP, // "delete: error in file or url name expression"
EE_DELETE_NOOBJ, // "delete: can't find object"
EE_DISABLE_NOOBJ, // "disable: can't find object"
EE_DISPATCH_NOFILEYET, // "Stack: stack has not been given a file name"
EE_DIVIDE_BADARRAY, // "divide: error in matrix operation"
EE_DIVIDE_BADDEST, // "divide: destination has a bad format (numeric?)"
EE_DIVIDE_BADSOURCE, // "divide: error in source expression"
EE_DIVIDE_CANTSET, // "divide: can't set destination"
EE_DIVIDE_MISMATCH, // "divide: can't divide scalar by array"
EE_MATH_RANGE, // "numeric: range error (overflow)"
EE_MATH_ZERO, // "numeric: divide by zero"
EE_DIV_BADARRAY, // "Operators div: error in matrix operation"
EE_DIV_BADLEFT, // "Operators div: error in left operand"
EE_DIV_BADRIGHT, // "Operators div: error in right operand"
EE_DIV_MISMATCH, // "Operators div: can't divide scalar by matrix"
EE_UNUSED_0158, // "UNUSED"
EE_UNUSED_0159, // "UNUSED"
EE_DO_ABORT, // "do: aborted"
EE_DO_BADCOMMAND, // "do: error in source expression"
EE_DO_BADEXEC, // "do: error in statement"
EE_DO_BADEXP, // "do: error in expression"
EE_DO_BADLANG, // "do: error in language expression"
EE_DO_BADLINE, // "do: unexpected end of line in source expression"
EE_DO_NOCOMMAND, // "do: can't find command"
EE_DO_NOTCOMMAND, // "do: not a command"
EE_DO_NOTLICENSED, // "do: license limit exceeded"
EE_DOMENU_BADEXP, // "doMenu: error in expression"
EE_DOMENU_DONTKNOW, // "doMenu: don't know this menu item"
EE_DRAG_ABORT, // "drag: script aborted"
EE_DRAG_BADBUTTON, // "drag: bad \"button\" number"
EE_DRAG_BADENDLOC, // "drag: bad end point expression"
EE_DRAG_ENDNAP, // "drag: end point is not a point"
EE_DRAG_BADSTARTLOC, // "drag: bad start point expression"
EE_DRAG_STARTNAP, // "drag: start point is not a point"
EE_DRIVERNAMES_BADTYPE, // "driverNames: error in type expression"
EE_DRIVES_BADTYPE, // "drives: error in type expression"
EE_EDIT_BADTARGET, // "edit: can't find object"
EE_ENCRYPT_BADSOURCE, // "encrypt: error in source expression"
EE_EQUAL_OPS, // "Operators =: error in operand"
EE_EXP10_BADSOURCE, // "exp10: error in source expression"
EE_UNUSED_0183, // "UNUSED"
EE_EXP1_BADSOURCE, // "exp1: error in source expression"
EE_UNUSED_0185, // "UNUSED"
EE_EXP2_BADSOURCE, // "exp2: error in source expression"
EE_UNUSED_0187, // "UNUSED"
EE_EXPORT_BADNAME, // "export: error in file (or mask file) name expression"
EE_EXPORT_CANTOPEN, // "export: can't open file (or mask file)"
EE_EXPORT_CANTWRITE, // "export: can't write to file, mask file, or container"
EE_EXPORT_NOSELECTED, // "export: no image selected, or image not open"
EE_EXPORT_NOTANIMAGE, // "export: selected object is not an image"
EE_EXPRESSION_NFACTOR, // "Expression: error in numeric factor"
EE_EXPRESSION_SFACTOR, // "Expression: error in string factor"
EE_EXP_BADSOURCE, // "exp: error in source expression"
EE_UNUSED_0196, // "UNUSED"
EE_EXTENTS_BADSOURCE, // "extents: error in variable expression"
EE_FACTOR_BADLEFT, // "Factor: error in left operand"
EE_FACTOR_BADRIGHT, // "Factor: error in right operand"
EE_FIELD_BADTEXTATTS, // "Field: bad text attributes"
EE_FIELD_HILITEDNAN, // "Field: hilitedLine is not an integer"
EE_FIELD_SCROLLBARWIDTHNAN, // "Field: scrollbarWidth is not an integer"
EE_FIELD_SHIFTNAN, // "Field: shift is not an integer"
EE_FIELD_TABSNAN, // "Field: tabstops is not a positive integer"
EE_FILES_NOPERM, // "files: no permission to list files or directories"
EE_FILTER_CANTGET, // "filter: bad source string"
EE_FILTER_CANTGETPATTERN, // "filter: bad pattern string"
EE_FILTER_CANTSET, // "filter: can't set destination"
EE_FIND_BADSTRING, // "find: bad source string"
EE_FLIP_NOIMAGE, // "flip: can't find image"
EE_FLIP_NOTIMAGE, // "flip: object is not an editable image"
EE_FLUSHEVENTS_BADTYPE, // "flushEvents: bad event type"
EE_FOCUS_BADOBJECT, // "focus: not a valid control"
EE_FONTNAMES_BADTYPE, // "fontNames: error in type expression"
EE_FONTSIZES_BADFONTNAME, // "fontSizes: bad font name"
EE_FONTSTYLES_BADFONTNAME, // "fontStyles: bad font name"
EE_FONTSTYLES_BADFONTSIZE, // "fontStyles: bad font size"
EE_FORMAT_BADSOURCE, // "format: bad format string or parameter mismatch"
EE_FUNCTION_BADFUNCTION, // "Function: error in function handler"
EE_FUNCTION_BADSOURCE, // "Function: error in source expression"
EE_FUNCTION_CANTEVALN, // "Function: source is not a number"
EE_FUNCTION_NAN, // "Function: is not a number"
EE_GET_BADEXP, // "get: error in expression"
EE_GET_CANTSET, // "get: can't set destination"
EE_GLOBALLOC_NAP, // "globalLoc: coordinate is not a point"
EE_GO_BADBACKGROUNDEXP, // "go: error in background expression"
EE_GO_BADCARDEXP, // "go: error in card expression"
EE_GO_BADSTACKEXP, // "go: error in stack expression"
EE_GO_BADWINDOWEXP, // "go: error in window expression"
EE_GO_CANTATTACH, // "go: can't attach menu to this object type"
EE_GO_NODEST, // "go: can't find destination"
EE_GRAB_NOOBJ, // "grab: can't find object"
EE_GRAPHIC_NAN, // "graphic: not an integer"
EE_GREATERTHANEQUAL_OPS, // "Operators >=: error in operands"
EE_GREATERTHAN_OPS, // "Operators >: error in operands"
EE_GROUP_BACKSIZENAP, // "Group: backSize is not a point"
EE_GROUP_HILITEDNAN, // "Group: hilitedButton is not an integer"
EE_GROUP_NOOBJ, // "Group: bad object type"
EE_GROUPING_BADRIGHT, // "Operators (): error in right operand"
EE_HANDLER_ABORT, // "Handler: aborted"
EE_HANDLER_BADSTATEMENT, // "Handler: error in statement"
EE_HANDLER_BADPARAM, // "Handler: error in parameter expression"
EE_HANDLER_BADPARAMINDEX, // "Handler: not a valid parameter index"
EE_HASMEMORY_BADAMOUNT, // "hasMemory: bad amount expression"
EE_HIDE_BADEFFECT, // "hide: error in visual effect expression"
EE_HIDE_NOOBJ, // "hide: can't find object"
EE_HOSTADDRESS_BADSOCKET, // "hostAddress: error in socket expression"
EE_HOSTATON_BADADDRESS, // "hostAddressToName: error in address expression"
EE_HOSTNAME_BADNAME, // "hostName: error in name expression"
EE_HOSTNTOA_BADNAME, // "hostNameToAddress: error in name expression"
EE_IF_ABORT, // "if-then: aborted"
EE_IF_BADCOND, // "if-then: error in condition expression"
EE_IF_BADSTATEMENT, // "if-then: error in statement"
EE_IMAGE_BADPIXMAP, // "Image: bad pixmap id"
EE_IMAGE_HOTNAP, // "Image: hotspot is not an integer"
EE_OBJECT_IDNAN, // "Image: id is not an integer"
EE_OBJECT_IDINUSE, // "Image: id is already in use by another object"
EE_IMAGE_NOTOPEN, // "Image: image must be open to set id"
EE_IMAGE_XHOTNAN, // "Image: hotSpot x is not an integer"
EE_IMAGE_YHOTNAN, // "Image: hotSpot y is not an integer"
EE_IMPORT_BADNAME, // "import: error in expression"
EE_IMPORT_CANTOPEN, // "import: can't open file, mask file or display"
EE_IMPORT_CANTREAD, // "import: can't read file, mask file or display"
EE_IMPORT_LOCKED, // "import: destination stack is locked (cantModify)"
EE_INSERT_BADTARGET, // "insert: can't find object"
EE_INSERT_NOTLICENSED, // "insert: license limit exceeded"
EE_INTERSECT_NOOBJECT, // "intersect: two objects required"
EE_IS_BADLEFT, // "Operators is: error in left operand"
EE_IS_BADRIGHT, // "Operators is: error in right operand"
EE_IS_BADOPS, // "Operators is: can't compare operands"
EE_IS_WITHINNAP, // "Operators is: left operand of 'within' is not a point"
EE_IS_WITHINNAR, // "Operators is: right operand of 'within' is not a rectangle"
EE_ISNUMBER_BADSOURCE, // "isNumber: error in source expression"
EE_ISOTOMAC_BADSOURCE, // "isoToMac: error source expression"
EE_ITEM_BADLEFT, // "Operators ,: error in left operand"
EE_ITEM_BADRIGHT, // "Operators ,: error in right operand"
EE_KEYS_BADSOURCE, // "keys: parameter is not a variable"
EE_KILL_BADNAME, // "kill: no such process"
EE_KILL_BADNUMBER, // "kill: bad number"
EE_LAUNCH_BADAPPEXP, // "launch: error in application expression"
EE_LENGTH_BADSOURCE, // "length: error in source expression"
EE_LESSTHANEQUAL_OPS, // "Operators <=: error in operands"
EE_LESSTHAN_OPS, // "Operators <: error in operands"
EE_LN1_BADSOURCE, // "ln1: error in source expression"
EE_UNUSED_0285, // "UNUSED"
EE_LN_BADSOURCE, // "ln: error in source expression"
EE_UNUSED_0287, // "UNUSED"
EE_LOAD_BADURLEXP, // "load: error in url expression"
EE_LOAD_BADMESSAGEEXP, // "load: error in message expression"
EE_LOCALLOC_NAP, // "localLoc: coordinate is not a point"
EE_LOG10_BADSOURCE, // "log10: error in source expression"
EE_UNUSED_0292, // "UNUSED"
EE_LOG2_BADSOURCE, // "log2: error in source expression"
EE_UNUSED_0294, // "UNUSED"
EE_LONGFILEPATH_BADSOURCE, // "longFilePath: error in file expression"
EE_MACTOISO_BADSOURCE, // "macToIso: error source expression"
EE_MARK_BADCARD, // "mark: bad card expression"
EE_MARK_BADSTRING, // "mark: error in find expression"
EE_MATCH_BADDEST, // "matchChunk: can't set destination variable"
EE_MATCH_BADPARAM, // "matchChunk: bad or missing parameter"
EE_MATCH_BADPATTERN, // "matchChunk: error in pattern expression"
EE_MATCH_BADSOURCE, // "matchChunk: error in source expression"
EE_MATRIX_RANGE, // "matrix: range error in matrix operation"
EE_MATRIXMULT_BADSOURCE, // "matrixMultiply: error in source expression"
EE_MATRIXMULT_MISMATCH, // "matrixMultiply: can't multiply these arrays"
EE_MAX_BADSOURCE, // "max: error in source expression"
EE_MCISENDSTRING_BADSOURCE, // "MCISendString: error in source expression"
EE_MD5DIGEST_BADSOURCE, // "MD5digest: error in source expression"
EE_MEDIAN_BADSOURCE, // "median: error in source expression"
EE_MERGE_BADSOURCE, // "merge: error in source expression"
EE_MINUS_BADARRAY, // "Operators -: can't subtract array from scalar"
EE_MINUS_BADLEFT, // "Operators -: error in left operand"
EE_MINUS_BADRIGHT, // "Operators -: error in right operand"
EE_MINUS_MISMATCH, // "Operators -: range error (overflow) in array operation"
EE_UNUSED_0315, // "UNUSED"
EE_MIN_BADSOURCE, // "min: error in source expression"
EE_MOD_BADARRAY, // "Operators mod: error in matrix operation"
EE_MOD_BADLEFT, // "Operators mod: error in left operand"
EE_MOD_BADRIGHT, // "Operators mod: error in right operand"
EE_MOD_MISMATCH, // "Operators mod: can't divide scalar by matrix"
EE_UNUSED_0321, // "UNUSED"
EE_UNUSED_0322, // "UNUSED"
EE_MOUSE_BADSOURCE, // "mouse: error in source expression"
EE_MOVE_ABORT, // "move: script aborted"
EE_MOVE_BADOBJECT, // "move: can't find object"
EE_MOVE_BADENDLOC, // "move: bad end point expression"
EE_MOVE_BADDURATION, // "move: bad duration expression"
EE_MOVE_DURATIONNAN, // "move: duration is not a number"
EE_MOVE_ENDNAP, // "move: end point is not a point"
EE_MOVE_BADSTARTLOC, // "move: bad start point expression"
EE_MOVE_STARTNAP, // "move: start point is not a point"
EE_MULTIPLY_BADARRAY, // "multiply: error in matrix operation"
EE_MULTIPLY_BADDEST, // "multiply: destination has a bad format (numeric?)"
EE_MULTIPLY_BADSOURCE, // "multiply: error in source expression"
EE_MULTIPLY_CANTSET, // "multiply: can't set destination"
EE_MULTIPLY_MISMATCH, // "multiply: can't multiply scalar by array"
EE_UNUSED_0337, // "UNUSED"
EE_NOTEQUAL_OPS, // "Operators <>: error in operands"
EE_NOT_BADRIGHT, // "Operators not: error in right operand"
EE_NOTBITS_BADRIGHT, // "Operators bitNot: error in right operand"
EE_NUMTOCHAR_BADSOURCE, // "numToChar: error in source expression"
EE_OBJECT_BADALIGN, // "Object: bad textAlign expression"
EE_OBJECT_BADCOLOR, // "Object: unknown color"
EE_OBJECT_BADCOLORS, // "Object: error in colors"
EE_OBJECT_BADRELAYER, // "Object: can't set layer (card not open, or control in group)"
EE_OBJECT_BADSTYLE, // "Object: not a textStyle"
EE_OBJECT_CANTREMOVE, // "Object: stack locked, or object's script is executing"
EE_OBJECT_GETNOPROP, // "Object: object does not have this property"
EE_OBJECT_LAYERNAN, // "Object: height is not an integer"
EE_OBJECT_LOCNAP, // "Object: layer is not an integer"
EE_OBJECT_MARGINNAN, // "Object: margin is not an integer"
EE_OBJECT_NAB, // "Object: value is not a boolean (true or false)"
EE_OBJECT_NAME, // "Object Name:"
EE_OBJECT_NAN, // "Object: property is not an integer"
EE_OBJECT_NAP, // "Object: coordinate is not a point"
EE_OBJECT_NAR, // "Object: rectangle does not have 4 points"
EE_OBJECT_NOHOME, // "Object: no Home stack"
EE_OBJECT_PIXELNAN, // "Object: pixel value is not an integer"
EE_OBJECT_PIXMAPNAN, // "Object: pixmap is not an integer"
EE_OBJECT_SCRIPTEXECUTING, // "Object: can't set script while it is executing"
EE_OBJECT_SETNOPROP, // "Object: can't set this property"
EE_OBJECT_TEXTHEIGHTNAN, // "Object: textheight is not an integer"
EE_OBJECT_TEXTSIZENAN, // "Object: textsize is not an integer"
EE_OFFSET_BADOFFSET, // "offset: error in start offset expression"
EE_OFFSET_BADPART, // "offset: error in part expression"
EE_OFFSET_BADWHOLE, // "offset: error in whole expression"
EE_OPEN_BADMESSAGE, // "open: error in message expression"
EE_OPEN_BADNAME, // "open: error in name expression"
EE_OPEN_NOPERM, // "open: no permission to open files or processes"
EE_OR_BADLEFT, // "Operators or: error in left operand"
EE_OR_BADRIGHT, // "Operators or: error in right operand"
EE_ORBITS_BADLEFT, // "Operators bitOr: error in left operand"
EE_ORBITS_BADRIGHT, // "Operators bitOr: error in right operand"
EE_OVER_BADARRAY, // "Operators /: error in matrix operation"
EE_OVER_BADLEFT, // "Operators /: error in left operand"
EE_OVER_BADRIGHT, // "Operators /: error in right operand"
EE_OVER_MISMATCH, // "Operators /: can't divide scalar by matrix"
EE_UNUSED_0378, // "UNUSED"
EE_UNUSED_0379, // "UNUSED"
EE_PARAM_BADEXP, // "param: error in expression"
EE_PARAM_BADINDEX, // "param: bad parameter index"
EE_PARAM_BADSOURCE, // "param: error in source expression"
EE_PARAM_NAN, // "param: is not a number"
EE_PASTE_LOCKED, // "paste: stack is locked (cantModify)"
EE_PEERADDRESS_BADSOCKET, // "peerAddress: error in socket expression"
EE_PLACE_ALREADY, // "place: group is not in this stack or is already on this card"
EE_PLACE_NOBACKGROUND, // "place: can't find group"
EE_PLACE_NOCARD, // "place: can't find card"
EE_PLACE_NOTABACKGROUND, // "place: source is not a group, or cannot be used as a background"
EE_PLACE_NOTACARD, // "place: destination is not a card"
EE_PLAY_BADCLIP, // "play: can't get sound or movie name"
EE_PLAY_BADLOC, // "play: bad movie location"
EE_PLAY_BADOPTIONS, // "play: bad movie options"
EE_PLUS_BADLEFT, // "Operators +: error in left operand"
EE_PLUS_BADRIGHT, // "Operators +: error in right operand"
EE_UNUSED_0396, // "UNUSED"
EE_POP_CANTSET, // "pop: can't set destination"
EE_POST_BADDESTEXP, // "post: can't get source"
EE_POST_BADSOURCEEXP, // "post: can't get destination"
EE_POW_BADLEFT, // "pow: error in left operand"
EE_POW_BADRIGHT, // "pow: error in right operand"
EE_UNUSED_0402, // "UNUSED"
EE_PRINT_CANTGETCOORD, // "print: can't get 'from' or 'to' coordinates"
EE_PRINT_CANTGETCOUNT, // "print: can't get number of cards"
EE_PRINT_CANTGETRECT, // "print: can't get rectangle"
EE_PRINT_ERROR, // "print: error printing"
EE_PRINT_IOERROR, // "print: error writing file (disk full?)"
EE_PRINT_NAP, // "print: coordinate not a point"
EE_PRINT_NAR, // "print: expression is not a rectangle"
EE_PRINT_NOTACARD, // "print: not a card"
EE_PRINT_NOTOPEN, // "print: card or stack must be open to print it"
EE_PRINT_NOTARGET, // "print: no card specified"
EE_PROPERTY_BADARCANGLE, // "arcAngle: not an integer"
EE_PROPERTY_BADBLINKRATE, // "blinkRate: not a number"
EE_PROPERTY_BADCOLOR, // "penColor: bad color"
EE_PROPERTY_BADCOLORS, // "colormap: bad color name or value"
EE_PROPERTY_BADCOUNTN, // "Object: error counting objects as number"
EE_PROPERTY_BADCOUNTS, // "Object: error counting objects as text"
EE_PROPERTY_BADDRAGSPEED, // "dragSpeed: not a number"
EE_PROPERTY_BADEFFECTRATE, // "effectRate: not a number"
EE_PROPERTY_BADEXTENDKEY, // "extendKey: not a number"
EE_PROPERTY_BADEXPRESSION, // "Property: bad array expression"
EE_PROPERTY_BADGRIDSIZE, // "gridSize: not an integer"
EE_PROPERTY_BADIDLERATE, // "idleRate: not a number"
EE_PROPERTY_BADLINESIZE, // "lineSize: not an integer"
EE_PROPERTY_BADMOVESPEED, // "moveSpeed: not a number"
EE_PROPERTY_BADMULTISPACE, // "multiSpace: not a number"
EE_PROPERTY_BADPOLYSIDES, // "polySides: not an integer"
EE_PROPERTY_BADREPEATDELAY, // "repeatDelay: not a number"
EE_PROPERTY_BADREPEATRATE, // "repeatRate: not a number"
EE_PROPERTY_BADDOUBLEDELTA, // "doubleClickDelta: not an integer"
EE_PROPERTY_BADDOUBLETIME, // "doubleClickTime: not a number"
EE_PROPERTY_BADROUNDRADIUS, // "roundRadius: not an integer"
EE_PROPERTY_BADSLICES, // "slices: not an integer"
EE_PROPERTY_BADSTARTANGLE, // "startAngle: not an integer"
EE_PROPERTY_BADTRACEDELAY, // "traceDelay: not a number"
EE_PROPERTY_BADTRACESTACK, // "traceStack: not a stack name"
EE_PROPERTY_BADPRINTPROP, // "print: bad property value"
EE_PROPERTY_BADSYNCRATE, // "syncRate: not a number"
EE_PROPERTY_BADTOOLDELAY, // "tooltipDelay: not a number"
EE_PROPERTY_BADTYPERATE, // "typeRate: not a number"
EE_PROPERTY_BADUSERLEVEL, // "userLevel: not an integer"
EE_PROPERTY_BEEPNAN, // "beep: not an integer"
EE_PROPERTY_BRUSHNAN, // "brush: not an integer"
EE_PROPERTY_BRUSHNOIMAGE, // "brush: can't find image"
EE_PROPERTY_BRUSHPATNAN, // "brushPattern: not a valid image id"
EE_PROPERTY_BRUSHPATNOIMAGE, // "brushPattern: can't find image"
EE_PROPERTY_CANTSET, // "Object: no object to set property"
EE_PROPERTY_CANTSETOBJECT, // "Object: can't set object property"
EE_PROPERTY_CURSORNAN, // "cursor: not an integer"
EE_PROPERTY_CURSORNOIMAGE, // "cursor: can't find image"
EE_PROPERTY_NAB, // "Property: value is not a boolean (\"true\" or \"false\")"
EE_PROPERTY_NAN, // "Property: value is not a number"
EE_PROPERTY_NODEFAULTSTACK, // "defaultStack: can't find stack"
EE_PROPERTY_NODEFAULTMENUBAR, // "defaultMenuBar: can't find group"
EE_PROPERTY_NOPROP, // "Object: does not have this property"
EE_PROPERTY_NOTANUM, // "Object: property is not an integer"
EE_PROPERTY_PENPATNAN, // "penPattern: not a valid image id"
EE_PROPERTY_PENPATNOIMAGE, // "penPattern: can't find image"
EE_PROPERTY_RANDOMSEEDNAN, // "randomSeed: property is not an integer"
EE_PROPERTY_SOCKETTIMEOUTNAN, // "socketTimeout: not a number"
EE_PROPERTY_UMASKNAN, // "umask: property is not an integer"
EE_PUSH_NOTACARD, // "push: object is not a card"
EE_PUSH_NOTARGET, // "push: can't find card"
EE_PUT_BADEXP, // "put: error in expression"
EE_PUT_CANTSET, // "put: can't set destination"
EE_PUT_CANTSETINTO, // "put: can't put into destination"
EE_QUERYREGISTRY_BADEXP, // "queryRegistry: error in source expression"
EE_RANDOM_BADSOURCE, // "random: error in source expression"
EE_READ_ABORT, // "read: aborted"
EE_READ_BADAT, // "read: error in 'at' expression"
EE_READ_BADCOND, // "read: error in condition expression"
EE_READ_BADEXP, // "read: error in count expression"
EE_READ_ERROR, // "read: error reading"
EE_READ_NAN, // "read: count is not an integer"
EE_READ_NOCHARACTER, // "read: error in 'until' expression"
EE_READ_NOFILE, // "read: file is not open"
EE_READ_NONUMBER, // "read: error in 'for' expression"
EE_READ_NOPROCESS, // "read: process is not open"
EE_RECORD_BADFILE, // "record: error in file expression"
EE_RECORDCOMPRESSION_BADTYPE, // "recordCompression: type must be 4 characters"
EE_RECORDINPUT_BADTYPE, // "recordInput: type must be 4 characters"
EE_REMOVE_NOOBJECT, // "remove: can't find object"
EE_REMOVE_NOTABACKGROUND, // "remove: object is not a group"
EE_REMOVE_NOTACARD, // "remove: object is not a card"
EE_RENAME_BADSOURCE, // "rename: error in source expression"
EE_RENAME_BADDEST, // "rename: error in destination expression"
EE_REPEAT_ABORT, // "repeat: aborted"
EE_REPEAT_BADFORCOND, // "repeat: error in 'for' condition expression"
EE_REPEAT_BADSTATEMENT, // "repeat: error in statement"
EE_REPEAT_BADUNTILCOND, // "repeat: error in 'until' condition expression"
EE_REPEAT_BADWHILECOND, // "repeat: error in 'while' condition expression"
EE_REPEAT_BADWITHEND, // "repeat: error in 'with' end condition expression"
EE_REPEAT_BADWITHSTART, // "repeat: error in 'with' start condition expression"
EE_REPEAT_BADWITHSTEP, // "repeat: error in 'with' step condition expression"
EE_REPEAT_BADWITHVAR, // "repeat: error setting 'with' variable"
EE_REPLACE_CANTSET, // "replace: can't set container"
EE_REPLACE_BADPATTERN, // "replace: error in pattern expression"
EE_REPLACE_BADREPLACEMENT, // "replace: error in replacement expression"
EE_REPLACE_BADCONTAINER, // "replace: error in container expression"
EE_REPLACETEXT_BADPATTERN, // "replaceText: bad parameter"
EE_REPLACETEXT_BADSOURCE, // "replaceText: bad source string"
EE_REPLY_BADKEYWORDEXP, // "reply: error in keyword expression"
EE_REPLY_BADMESSAGEEXP, // "reply: error in message expression"
EE_REQUEST_BADKEYWORDEXP, // "request: error in keyword expression"
EE_REQUEST_BADMESSAGEEXP, // "request: error in message expression"
EE_REQUEST_BADPROGRAMEXP, // "request: error in program expression"
EE_REQUEST_NOPERM, // "request: no permission to request that"
EE_RESOURCES_BADPARAM, // "getResources: error in expression"
EE_RESOURCES_NOPERM, // "getResources: no permission to get that"
EE_RETURN_BADEXP, // "return: error in expression"
EE_REVERT_HOME, // "revert: can't revert Home stack"
EE_ROTATE_NOIMAGE, // "rotate: error in object expression"
EE_ROTATE_NOTIMAGE, // "rotate: object is not an editable image"
EE_ROTATE_BADANGLE, // "rotate: error in angle expression"
EE_ROUND_BADSOURCE, // "round: error in source or digit expression"
EE_SAVE_BADNOFILEEXP, // "save: error in file name expression"
EE_SAVE_NOPERM, // "save: saving disabled"
EE_SAVE_NOTARGET, // "save: can't find stack to save"
EE_SAVE_NOTASTACK, // "save: object is not a stack"
EE_SEEK_BADNAME, // "seek: error in file name expression"
EE_SEEK_BADWHERE, // "seek: error in offset expression"
EE_SEEK_NOFILE, // "seek: file is not open"
EE_SELECT_BADTARGET, // "select: can't select target"
EE_SELECTED_BADSOURCE, // "selectedChunk: error in button or field expression"
EE_SELECTEDBUTTON_BADFAMILY, // "selectedButton: bad family expression"
EE_SELECTEDBUTTON_BADPARENT, // "selectedButton: bad parent object expression"
EE_SEND_BADEXEC, // "send: error in message handler execution"
EE_SEND_BADEXP, // "send: error in message expression"
EE_SEND_BADINEXP, // "send: error in 'in' expression"
EE_SEND_BADPROGRAMEXP, // "send: error in program expression"
EE_SEND_BADTARGET, // "send: bad target expression"
EE_SEND_NOPERM, // "send: no permission to send that"
EE_SET_BADEXP, // "set: error in source expression"
EE_SET_BADSET, // "set: can't set property"
EE_SETREGISTRY_NOPERM, // "setRegistry: no permission to get or set registry"
EE_SETREGISTRY_BADEXP, // "setRegistry: error in source expression"
EE_SHELL_ABORT, // "shell: aborted"
EE_SHELL_BADCOMMAND, // "shell: can't run shell command"
EE_SHELL_BADSOURCE, // "shell: error in source expression"
EE_SHELL_NOPERM, // "shell: no permission to run commands"
EE_SHORTFILEPATH_BADSOURCE, // "shortFilePath: error in file expression"
EE_SHOW_BADEFFECT, // "show: error in visual effect expression"
EE_SHOW_BADLOCATION, // "show: error in location expression"
EE_SHOW_BADNUMBER, // "show: error in number of cards expression"
EE_SHOW_NOLOCATION, // "show: location is not in proper x,y form"
EE_SHOW_NOOBJ, // "show: can't find object"
EE_SIN_BADSOURCE, // "sin: error in source expression"
EE_UNUSED_0549, // "UNUSED"
EE_SORT_BADTARGET, // "sort: can't find object to sort"
EE_SORT_CANTSORT, // "sort: error sorting"
EE_SORT_NOTARGET, // "sort: can't find field"
EE_SPECIALFOLDERPATH_BADPARAM, // "specialFolderPath: error in type expression"
EE_SQRT_BADSOURCE, // "sqrt: error in source expression"
EE_UNUSED_0555, // "UNUSED"
EE_STACK_BADDECORATION, // "Stack: bad decoration"
EE_STACK_BADID, // "Stack: invalid id (must be greater than current id)"
EE_STACK_BADKEY, // "Stack: invalid key"
EE_STACK_BADSUBSTACK, // "Stack: bad substack name"
EE_STACK_CANTSETMAINSTACK, // "Stack: can't set mainStack (has substacks?)"
EE_STACK_ICONNAN, // "Stack: deskIcon is not an integer"
EE_STACK_LEVELNAN, // "Stack: userLevel is not an integer"
EE_STACK_MINMAXNAN, // "Stack: size is not an integer"
EE_STACK_NOKEY, // "Stack: stack is password protected"
EE_STACK_NOMAINSTACK, // "Stack: can't find mainStack"
EE_STACK_NOTMAINSTACK, // "Stack: stack is not a mainStack"
EE_STACK_EXTERNALERROR, // "Stack: error in external function handler"
EE_START_BADTARGET, // "start: can't find object"
EE_START_LOCKED, // "start: stack is locked"
EE_START_NOTABACKGROUND, // "start: expression is not a group"
EE_START_NOTLICENSED, // "start: license limit exceeded"
EE_STATEMENT_BADPARAM, // "Handler: error in source expression"
EE_STATEMENT_BADCOMMAND, // "Handler: can't find handler"
EE_STDDEV_BADSOURCE, // "stdDev: error in expression"
EE_STOP_BADTARGET, // "stop: error in expression"
EE_STOP_NOTABACKGROUND, // "stop: target is not a group"
EE_SUBTRACT_BADARRAY, // "subtract: error in matrix operation"
EE_SUBTRACT_BADDEST, // "subtract: destination has a bad format (numeric?)"
EE_SUBTRACT_BADSOURCE, // "subtract: error in source expression"
EE_SUBTRACT_CANTSET, // "subtract: can't set destination"
EE_SUBTRACT_MISMATCH, // "subtract: can't subtract array from scalar"
EE_SUBWINDOW_BADEXP, // "subwindow: error in expression"
EE_SUBWINDOW_NOSTACK, // "subwindow: can't find stack or button"
EE_SUM_BADSOURCE, // "sum: error in source expression"
EE_SWITCH_BADCOND, // "switch: error in condition expression"
EE_SWITCH_BADCASE, // "switch: error in case expression"
EE_SWITCH_BADSTATEMENT, // "switch: error in statement"
EE_TAN_BADSOURCE, // "textHeightSum: can't find object"
EE_UNUSED_0589, // "UNUSED"
EE_TEXT_HEIGHT_SUM_NOOBJECT, // "tan: domain error"
EE_THERE_BADSOURCE, // "there: error in source expression"
EE_THROW_BADERROR, // "throw: error in source expression"
EE_TIMES_BADARRAY, // "Operators *: error in matrix operation"
EE_TIMES_BADLEFT, // "Operators *: error in left operand"
EE_TIMES_BADRIGHT, // "Operators *: error in right operand"
EE_UNUSED_0596, // "UNUSED"
EE_TOLOWER_BADSOURCE, // "toLower: error in source expression"
EE_TOPSTACK_BADSOURCE, // "topStack: error in source expression"
EE_TOUPPER_BADSOURCE, // "toUpper: error in source expression"
EE_TRANSPOSE_BADSOURCE, // "transpose: source is not a variable"
EE_TRANSPOSE_MISMATCH, // "transpose: can't transpose this array"
EE_TRUNC_BADSOURCE, // "trunc: error in source expression"
EE_TRY_BADSTATEMENT, // "try: error in statement"
EE_TYPE_ABORT, // "type: script aborted"
EE_TYPE_BADSTRINGEXP, // "type: bad string expression"
EE_UNGROUP_NOGROUP, // "ungroup: can't find group"
EE_UNGROUP_NOTAGROUP, // "ungroup: target is not a group"
EE_UNIDECODE_BADLANGUAGE, // "uniDecode: error in language expression"
EE_UNIDECODE_BADSOURCE, // "uniDecode: error in source expression"
EE_UNIENCODE_BADLANGUAGE, // "uniEncode: error in language expression"
EE_UNIENCODE_BADSOURCE, // "uniEncode: error in source expression"
EE_UNLOAD_BADURLEXP, // "unload: error in url expression"
EE_UNLOCK_BADEFFECT, // "unlock: expression is not a visual effect"
EE_URLDECODE_BADSOURCE, // "urlDecode: error in source expression"
EE_URLENCODE_BADSOURCE, // "urlEncode: error in source expression"
EE_URLSTATUS_BADSOURCE, // "urlStatus: error in url expression"
EE_VALUE_BADSOURCE, // "value: error in source expression"
EE_VALUE_ERROR, // "value: error executing expression"
EE_VALUE_NOOBJ, // "value: can't find object"
EE_VARIABLE_BADINDEX, // "Array: bad index expression"
EE_VARIABLE_NAC, // "Chunk: source is not a character"
EE_VARIABLE_NAN, // "Chunk: source is not a number"
EE_VISUAL_BADEXP, // "visual: bad effect expression"
EE_WAIT_ABORT, // "wait: aborted"
EE_WAIT_BADEXP, // "wait: error in expression"
EE_WAIT_NAN, // "wait: expression is not a number"
EE_WITHIN_NOCONTROL, // "within: can't find control"
EE_WITHIN_NAP, // "within: not a point"
EE_WRITE_BADEXP, // "write: error in expression"
EE_XORBITS_BADLEFT, // "Operators bitXor: error in left operand"
EE_XORBITS_BADRIGHT, // "Operators bitXor: error in right operand"
EE_PROPERTY_STACKFILEBADVERSION, // "Property stackFileVersion: not a valid version"
EE_PROPERTY_STACKFILEUNSUPPORTEDVERSION, // "Property stackFileVersion: version not supported"
EE_EXTERNAL_EXCEPTION, // "External handler: exception"
EE_EXPORT_EMPTYRECT, // "export: Empty rectangle"
EE_IMPORT_EMPTYRECT, // "import: Empty rectangle"
EE_DRAGDROP_BADACTION, // "Property dragAction: Unknown action"
EE_DRAGDROP_BADIMAGEOFFSET, // "Property dragImageOffset: Not a point"
EE_PROPERTY_BADDRAGDELTA, // "Property dragDelta: Not a number"
EE_CLIPBOARD_BADMIX, // "clipboard: invalid mix of data types"
EE_CLIPBOARD_BADTEXT, // "clipboard: invalid text"
EE_WRAP_BADARRAY, // "wrap: bad array"
EE_WRAP_BADLEFT, // "wrap: illegal type for left operand"
EE_WRAP_BADRIGHT, // "wrap: illegal type for right operand"
EE_WRAP_MISMATCH, // "wrap: type mismatch"
EE_UNUSED_0646, // "UNUSED"
EE_UNUSED_0647, // "UNUSED"
EE_BEGINSENDS_BADRIGHT, // "begins/ends with: illegal type for right operand"
EE_BEGINSENDS_BADLEFT, // "begins/ends with: illegal type for left operand"
EE_UNUSED_0650, // "UNUSED"
EE_UNUSED_0651, // "UNUSED"
EE_UNUSED_0652, // "UNUSED"
EE_UNUSED_0653, // "UNUSED"
EE_UNUSED_0654, // "UNUSED"
EE_UNUSED_0655, // "UNUSED"
EE_UNUSED_0656, // "UNUSED"
EE_UNUSED_0657, // "UNUSED"
EE_GRAPHIC_NAB, // "graphic: not a boolean"
EE_GRAPHIC_BADFILLRULE, // "graphic: bad fill rule"
EE_GRAPHIC_BADGRADIENTTYPE, // "graphic: bad gradient type"
EE_GRAPHIC_BADGRADIENTRAMP, // "graphic: bad gradient ramp"
EE_GRAPHIC_BADGRADIENTPOINT, // "graphic: bad gradient point"
EE_GRAPHIC_BADGRADIENTQUALITY, // "graphic: bad gradient quality"
EE_GRAPHIC_BADGRADIENTKEY, // "graphic: bad gradient key"
EE_GRAPHIC_BADCAPSTYLE, // "graphic: bad cap style"
EE_GRAPHIC_BADJOINSTYLE, // "graphic: bad join style"
EE_BYTETONUM_BADSOURCE, // "byteToNum: bad expression"
EE_NUMTOBYTE_BADSOURCE, // "numToByte: bad expression"
EE_ARRAYENCODE_BADSOURCE, // "arrayEncode: bad expression"
EE_ARRAYENCODE_FAILED, // "arrayEncode: failure"
EE_ARRAYDECODE_BADSOURCE, // "arrayDecode: bad expression"
EE_ARRAYDECODE_FAILED, // "arrayDecode: failure"
EE_PARENTSCRIPT_BADOBJECT, // "parentScript: bad object"
EE_DISPATCH_BADMESSAGEEXP, // "dispatch: bad message"
EE_DISPATCH_BADCOMMAND, // "dispatch: bad command"
EE_DISPATCH_BADTARGET, // "dispatch: bad target"
EE_QUERYREGISTRY_BADDEST, // "queryRegistry: bad destination"
EE_PARENTSCRIPT_CYCLICOBJECT, // "parentScript: loop in hierarchy"
EE_DISK_NOPERM, // "Security: disk access not allowed"
EE_NETWORK_NOPERM, // "Security: network access not allowed"
EE_PROCESS_NOPERM, // "Security: external command access not allowed"
EE_REGISTRY_NOPERM, // "Security: registry access not allowed"
NOTUSED__EE_STACK_NOPERM, // "<not used>"
EE_PRINT_NOPERM, // "Security: printer access not allowed"
EE_PRIVACY_NOPERM, // "Security: audio and camera access not allowed"
EE_BITMAPEFFECT_BADKEY, // ""
EE_BITMAPEFFECT_BADKEYFORTYPE, // ""
EE_BITMAPEFFECT_BADNUMBER, // ""
EE_BITMAPEFFECT_BADCOLOR, // ""
EE_BITMAPEFFECT_BADBLENDMODE, // ""
EE_BITMAPEFFECT_BADFILTER, // ""
EE_BITMAPEFFECT_BADTECHNIQUE, // ""
EE_BITMAPEFFECT_BADSOURCE, // ""
EE_BITMAPEFFECT_BADBOOLEAN, // ""
EE_SECUREMODE_BADCATEGORY, // ""
EE_SECUREMODE_APPLESCRIPT_NOPERM, // "Security: AppleScript access not allowed"
EE_SECUREMODE_DOALTERNATE_NOPERM, // "Security: alternate script execution not allowed"
EE_PROCESSTYPE_BADVALUE, // "processType: bad value"
EE_PROCESSTYPE_NOTPOSSIBLE, // "processType: cannot change"
NOTUSED__EE_VARIABLE_CONTENTS_LOCKED, // ""
NOTUSED__EE_VARIABLE_ELEMENT_LOCKED, // ""
EE_ENVDO_NOTSUPPORTED, // "do in browser: not supported"
EE_ENVDO_FAILED, // "do in browser: failed"
EE_GRAPHIC_BADEDITMODE, // "editMode: Bad value"
EE_EXPORT_BADPALETTE, // "export: Bad palette"
EE_EXPORT_BADPALETTESIZE, // "export: Invalid palette size"
EE_OPEN_BADOPTIONS, // "printing: Bad options array"
NOTUSED__EE_FEATURE_NOTSUPPORTED, // ""
EE_PRINT_UNKNOWNDST, // "printing: Unknown destination"
EE_OBJECT_NOTWHILEEDITING, // "object: cannot change id while in group edit mode"
EE_PRINTANCHOR_BADNAME, // "print: bad anchor name"
EE_PRINTANCHOR_BADLOCATION, // "print: bad anchor location"
EE_PRINTANCHOR_LOCATIONNAP, // "print: anchor location not a point"
EE_PRINTLINK_BADDEST, // "print: bad link destination"
EE_PRINTLINK_BADAREA, // "print: bad link area"
EE_PRINTLINK_AREANAR, // "print: link area not a rectangle"
EE_RANDOMBYTES_BADCOUNT, // "randomBytes: bad count"
EE_SHA1DIGEST_BADSOURCE, // "sha1Digest: bad source"
EE_STACKLIMIT_NAN, // "stackLimit: not a number"
EE_SECURITY_NOLIBRARY, // "could not load security library"
EE_GROUP_CANNOTBEBGORSHARED, // "group: cannot be background or shared (it is nested)"
EE_GROUP_CANNOTBENONSHARED, // "group: must be shared (it is placed on more than one card, or unplaced)"
EE_GROUP_NOBG, // "group: cannot group background or shared groups"
EE_PRINTBOOKMARK_BADTITLE, // "print: bad bookmark title"
EE_PRINTBOOKMARK_BADLEVEL, // "print: bad bookmark level"
EE_PRINTBOOKMARK_BADAT, // "print: bad bookmark position"
EE_PRINTBOOKMARK_BADINITIAL, // "print: bad bookmark initial state"
EE_SCRIPT_FILEINDEX, // "Script File Index:"
EE_INCLUDE_FILENOTFOUND, // "include: could not find file"
EE_SCRIPT_SYNTAXERROR, // "script: parsing error"
EE_SCRIPT_BADSTATEMENT, // "script: bad statement"
EE_INCLUDE_BADCONTEXT, // "include: not supported in this environment"
EE_INCLUDE_BADFILENAME, // "include: bad filename"
EE_INCLUDE_TOOMANY, // "include: nesting depth limit reached"
EE_REQUIRE_BADCONTEXT, // "require: not supported in this environment"
NOTUSED__EE_REQUIRE_BADFILENAME, // ""
NOTUSED__EE_REQUIRE_BADSTACK, // ""
EE_ERRORMODE_BADVALUE, // "errorMode: bad value"
EE_OUTPUTENCODING_BADVALUE, // "outputEncoding: bad value"
EE_OUTPUTLINEENDING_BADVALUE, // "outputLineEnding: bad value"
EE_SCRIPT_ERRORPOS, // "Script Error Position:"
EE_PROPERTY_BADNETWORKINTERFACE, // "defaultNetworkInterface: network interface must be an IPv4 address"
EE_CONTROL_BADLAYERMODE, // "layerMode: must be 'static', 'dynamic' or 'scrolling'"
EE_COMPOSITOR_INVALIDTILESIZE, // "tileSize: must be a power of two between 16 and 256"
EE_COMPOSITOR_UNKNOWNTYPE, // "tileCompositor: unknown type"
EE_COMPOSITOR_NOTSUPPORTED, // "tileCompositor: not supported on this platform"
EE_INTERSECT_BADTHRESHOLD, // "intersects: error in threshold expression"
EE_INTERSECT_ILLEGALTHRESHOLD, // "intersects: threshold must be a non-negative number, \"bounds\", \"pixels\" or \"opaque pixels\""
EE_SESSION_BADCONTEXT, // "session: not supported in this environment"
EE_SESSION_SAVE_PATH_BADVALUE, // "sessionSavePath: bad value"
EE_SESSION_LIFETIME_BADVALUE, // "sessionLifetime: bad value"
EE_SESSION_NAME_BADVALUE, // "sessionName: bad value"
EE_SESSION_ID_BADVALUE, // "sessionId: bad value"
EE_LOCK_BADRECT, // "lock: bad rect expr"
EE_LOCK_NAR, // "lock: not a rectangle"
EE_FIELD_BADLISTSTYLE, // "field: bad listStyle value"
EE_FIELD_FIRSTINDENTNAN, // "field: firstIndent must be an integer"
EE_FIELD_LEFTINDENTNAN, // "field: leftIndent must be an integer"
EE_FIELD_RIGHTINDENTNAN, // "field: rightIndent must be an integer"
EE_FIELD_SPACEBEFORENAN, // "field: spaceBefore must be an integer"
EE_FIELD_SPACEAFTERNAN, // "field: spaceAfter must be an integer"
EE_FIELD_BADLISTDEPTH, // "field: listDepth must be an integer between 1 and 16."
EE_FIELD_BORDERWIDTHNAN, // "field: borderWidth must be an integer"
EE_FIELD_LISTINDENTNAN, // "field: listIndent must be an integer"
EE_FIELD_PADDINGNAN, // "field: padding must be an integer"
EE_CHUNK_CANTSETUNICODEDEST, // "Chunk: can't store unicode to destination container"
EE_RELAYER_TARGETNOTCONTAINER, // "relayer: target not a container"
EE_RELAYER_NOTARGET, // "relayer: couldn't resolve target object"
EE_RELAYER_NOSOURCE, // "relayer: couldn't resolve source control"
EE_RELAYER_SOURCENOTCONTROL, // "relayer: source not a control"
EE_RELAYER_CARDNOTSAME, // "relayer: source and target not on the same card"
EE_RELAYER_LAYERNAN, // "relayer: layer not an integer"
EE_RELAYER_BADLAYER, // "relayer: bad layer expression"
EE_RELAYER_TARGETNOTCONTROL, // "relayer: target not a control"
EE_RELAYER_ILLEGALMOVE, // "relayer: cannot move a control into a descendent"
EE_RELAYER_OBJECTSVANISHED, // "relayer: required objects disappeared while processing"
EE_CONTROLATLOC_NAP, // "controlAtLoc: location not a point"
EE_DO_NOCALLER, // "do: no caller"
EE_READ_NOTVALIDFORDATAGRAM, // "read: invalid command for datagram socket"
EE_FIELD_LISTINDEXNAN, // "field: listIndex must be an integer"
EE_PROPERTY_BADIMAGECACHELIMIT, // "image cache limit: not a number"
EE_GROUP_DIFFERENTPARENT, // "controls don't have the same owner"
EE_UUID_BADTYPE, // "uuid: bad type expression"
EE_UUID_TOOMANYPARAMS, // "uuid: wrong number of arguments for specified type"
EE_UUID_UNKNOWNTYPE, // "uuid: unsupported type"
EE_UUID_BADNAMESPACEID, // "uuid: bad namespace expression"
EE_UUID_NAMESPACENOTAUUID, // "uuid: namespace not a uuid"
EE_UUID_BADNAME, // "uuid: bad name expression"
EE_UUID_NORANDOMNESS, // "uuid: not enough randomness available"
EE_AVGDEV_BADSOURCE, // "avgDev: error in source expression"
EE_GEO_MEAN_BADSOURCE, // "geometricMean: error in source expression"
EE_HAR_MEAN_BADSOURCE, // "harmonicMean: error in source expression"
EE_POP_STDDEV_BADSOURCE, // "pStdDev: error in source expression"
EE_POP_VARIANCE_BADSOURCE, // "pVariance: error in source expression"
EE_VARIANCE_BADSOURCE, // "variance: error in source expression"
EE_GROUP_NOTGROUPABLE, // "group: object cannot be grouped"
EE_MEASURE_TEXT_NOOBJECT, // "measureText: no object"
EE_FONT_BADFILEEXP, // "font: couldn't find font"
EE_EDIT_BADAT, // "edit script: bad at expression"
EE_STACK_BADFULLSCREENMODE, // "fullscreenmode: not a valid mode"
EE_PROPERTY_BADPIXELSCALE, // "pixelScale: not a valid scale value"
EE_STACK_BADSCALEFACTOR, // "scaleFactor: not a valid scale value"
EE_PROPERTY_PIXELSCALENOTSUPPORTED, // "pixelScale: the pixelScale property cannot be set on this platform"
EE_PROPERTY_USEPIXELSCALENOTSUPPORTED, // "usePixelScaling: the usePixelScaling property cannot be set on this platform"
EE_SECURE_BADNAME, // "secure: error in socket expression"
EE_PARAMCOUNT_NOHANDLER, // "paramCount: could not find handler"
EE_SEND_TOOMANYPENDING, // "send: too many pending messages"
EE_SECURE_BADHOST, // "secure: error in host name expression"
EE_OPEN_BADHOST, // "open: error in host name expression"
EE_CHUNK_BADEXTENTS, // "Chunk: bad extents provided"
EE_EXTERNAL_UNLICENSED, // "external: unlicensed"
EE_IMPORT_NOSELECTED, // "Import: no image selected, or image not open"
EE_RESOLVE_IMG_BADEXP, // "Resolve image: error in source expression"
EE_INTERNAL_BSDIFF_BADOLD, // "Internal BSDiff: error in old file expression"
EE_INTERNAL_BSDIFF_BADNEW, // "Internal BSDiff: error in new file expression"
EE_INTERNAL_BSDIFF_BADPATCH, // "Internal BSDiff: error in patch filename expression"
EE_INTERNAL_BOOTSTRAP_BADSTACK, // "Internal Bootstrap: error in stack file"
EE_IDE_BADARRAY, // "IDE script configure: error in settings expression"
EE_IDE_BADTEXT, // "IDE script replace: error in text expression"
EE_IDE_BADSCRIPT, // "IDE script classify: error in script expression"
EE_IDE_BADPATTERN, // "IDE filter control: error in pattern expression"
EE_ENGINE_PUT_BADVARIABLE, // "Engine PutInto: error in variable expression"
EE_ENGINE_DELETE_BADVARCHUNK, // "Engine DeleteVariableChunk: error in expression"
EE_IDE_EXTRACT_BADSEGMENT, // "IDE Extract: error in segment expression"
EE_IDE_EXTRACT_BADSECTION, // "IDE Extract: error in section name expression"
EE_IDE_EXTRACT_BADFILENAME, // "IDE Extract: error in filename expression"
EE_OUTPUT_BADFILENAME, // "MCInternalPayloadPatch: error in output filename expression"
EE_INTERNAL_TASKS_BADMODULE, // "MCInternalListTasksWithModule: error in module expression"
EE_INTERNAL_DELETE_BADFILENAME, // "MCInternalCanDeleteFile: error in filename expression"
EE_INTERNAL_DELETE_BADKEY, // "MCInternalCanDeleteKey: error in key expression"
EE_HANDLER_BADEXP, // "MCHandler: error in expression"
EE_TEXTDECODE_BADDATA, // "textDecode: bad data expression"
EE_TEXTDECODE_BADENCODING, // "textDecode: bad text encoding expression"
EE_TEXTDECODE_FAILED, // "textDecode: could not decode data"
EE_TEXTENCODE_BADTEXT, // "textEncode: bad text expression"
EE_TEXTENCODE_BADENCODING, // "textEncode: bad text encoding expression"
EE_TEXTENCODE_FAILED, // "textEncode: could not encode text"
EE_NORMALIZETEXT_BADFORM, // "normalizeText: bad normal form"
EE_NORMALIZETEXT_BADTEXT, // "normalizeText: bad text expression"
EE_CODEPOINTPROPERTY_BADCODEPOINT, // "codepointProperty: bad codepoint"
EE_CODEPOINTPROPERTY_BADPROPERTY, // "codepointProperty: bad property name"
EE_OPEN_BADENCODING, // "open: bad text encoding"
EE_OPEN_UNSUPPORTED_ENCODING, // "open: unsupported encoding"
EE_BIDIDIRECTION_BADSOURCE, // "bidiDirection: error in source expression"
EE_START_WONTCOMPILE, // "start: script of specified stack won't compile"
EE_HOSTNAME_BADMESSAGE, // "hostnameToAddress: callbacks are not allowed on server"
EE_EXPR_EVALERROR, // "Error evaluating expression"
EE_PROPERTY_NAC, // "Property: value is not a character"
EE_PROPERTY_NAS, // "Property: value is not a string"
EE_PROPERTY_NOTACOLOR, // "Property: value is not a color"
EE_PROPERTY_NOTARECT, // "Property: value is not a rectangle"
EE_PROPERTY_NOTAPOINT, // "Property: value is not a point"
EE_PROPERTY_NOTAINTPAIR, // "Property: value is not a pair of integers"
EE_PROPERTY_NOTAINTQUAD, // "Property: value is not a quadruple of integers"
EE_PROPERTY_BADENUMVALUE, // "Property: invalid enumeration value"
EE_BACKDROP_INVALIDVALUE, // "Backdrop: invalid value"
EE_PROPERTY_NOTANARRAY, // "Property: value is not an array"
EE_INTERNAL_PATCH_BADITEM, // "MCInternalPayloadPatch: error in patch item expression"
EE_INTERNAL_BASE_BADITEM, // "MCInternalPayloadPatch: error in base item expression"
EE_FLOOR_BADSOURCE, // "floor: bad parameter"
EE_CEIL_BADSOURCE, // "ceil: bad parameter"
EE_COMMANDARGUMENTS_BADPARAM, // "commandArguments: bad parameter"
EE_EXTENSION_ERROR_DOMAIN, // "extension: error occurred with domain"
EE_EXTENSION_ERROR_DESCRIPTION, // "extension: error occurred with description"
EE_EXTENSION_ERROR_FILE, // "extension: error occurred with file"
EE_EXTENSION_ERROR_LINE, // "extension: error occurred with line"
EE_LOAD_BADEXTENSION, // "load: error in extension expression"
EE_LOAD_BADRESOURCEPATH, // "load: error in resource path expression"
EE_SYSTEM_FUNCTION, // "System error: function"
EE_SYSTEM_CODE, // "System error: code"
EE_SYSTEM_MESSAGE, // "System error: message"
EE_IMPORT_BADARRAY, // "Import: bad array"
EE_IMPORT_NOTANOBJECTARRAY, // "Import: not an object array"
EE_CLIPBOARD_BADREP, // "clipboard: bad item type or data"
EE_CLIPBOARD_INSERTFAILED, // "clipboard: failed to insert item"
EE_CLIPBOARD_NOTLOCKED, // "clipboard: clipboard not locked"
EE_CLIPBOARD_ALREADYLOCKED, // "clipboard: already locked"
EE_CLIPBOARD_EXTERNALDATA, // "clipboard: needs to be cleared (contains external data)"
EE_GO_BADWIDGETEXP, // "go: error in widget expression"
EE_LAUNCH_BADWIDGETEXP, // "launch: error in widget expression"
EE_DO_BADWIDGETEXP, // "do: error in widget expression"
EE_DOCUMENTFILENAME_BADFILENAME, // "documentFilename: bad filename"
EE_SAVE_BADNOFORMATEXP, // "save: error in file format expression"
EE_REPLACE_BADFIELDCHUNK, // "replace: not a field chunk"
EE_INVOKE_TOOFEWARGS, // "call: too few arguments"
EE_INVOKE_TOOMANYARGS, // "call: too many arguments"
EE_SCRIPT_ONLY_STACK_NOPASSWORD, // "Stack: script only stacks can not be password protected"
EE_REVERT_NOSTACK, // "revert: can't find stack"
EE_VECTORDOT_BADLEFT, // "vectordot: error in first parameter"
EE_VECTORDOT_BADRIGHT, // "vectordot: error in second parameter"
EE_VECTORDOT_MISMATCH, // "vectordot: arrays are not key-wise compatible"
EE_FILES_BADFOLDER, // "files: error in folder parameter"
EE_FOLDERS_BADFOLDER, // "folders: error in folder parameter"
EE_NOTARGET, // "no target object"
EE_IMAGE_MUTABLELOCK, // "image: cannot change image while being edited"
EE_GRAPHIC_TOOMANYPOINTS, // "graphic : too many points"
EE_EXTENSION_ERROR_COLUMN, // "extension: error occurred with column"
EE_PARENTSCRIPT_EXECUTING, // "parentScript: can't change parent while parent script is executing"
EE_INVOKE_TYPEERROR, // "call: type conversion error"
EE_OPEN_BADFROMADDRESS, // "open: error in from address expression"
EE_MESSAGEDIGEST_BADTYPE, // "messageDigest: error in digest type parameter"
EE_MESSAGEDIGEST_BADDATA, // "messageDigest: error in message data parameter"
EE_SNAPSHOT_FAILED, // "snapshot: no screen"
EE_STACK_PASSWORD_NOT_SUPPORTED, // "stack: password protecting stacks not supported in this edition"
EE_FILES_BADKIND, // "files: error in kind parameter"
EE_FOLDERS_BADKIND, // "folders: error in kind parameter"
EE_BAD_LIBRARY_MAPPING, // "library mapping: bad mapping"
EE_FONTLANGUAGE_BADFONTNAME, // "fontLanguage: bad font name"
EE_BAD_PERMISSION_NAME, // "android permission: bad permission name"
EE_PROPERTY_NOTADATA, // "Property: value is not a data"
EE_SHOWNOTIFICATION_BADTITLE, // "showNotification: bad title expression"
EE_SHOWNOTIFICATION_BADBODY, // "showNotification: bad body expression"
EE_SHOWNOTIFICATION_BADTAG, // "showNotification: bad tag expression"
EE_CANCELNOTIFICATION_BADTAG, // "cancelNotification: bad tag expression"
EE_MATCHES_BADLEFT, // "Operators matches: error in left operand"
EE_MATCHES_BADRIGHT, // "Operators matches: error in right operand"
EE_IFF_BADCONDITION, // "iff: error evaluating condition"
EE_IFF_BADRESULT, // "iff: error evaluating result expression"
EE_STORECREDENTIAL_BADSERVICE, // "storeCredential: error in service expression"
EE_STORECREDENTIAL_BADACCOUNT, // "storeCredential: error in account expression"
EE_STORECREDENTIAL_BADSECRET, // "storeCredential: error in secret expression"
EE_RETRIEVECREDENTIAL_BADSERVICE, // "retrieveCredential: error in service expression"
EE_RETRIEVECREDENTIAL_BADACCOUNT, // "retrieveCredential: error in account expression"
EE_DELETECREDENTIAL_BADSERVICE, // "deleteCredential: error in service expression"
EE_DELETECREDENTIAL_BADACCOUNT, // "deleteCredential: error in account expression"
EE_SHARE_BADDATA, // "share: error evaluating data expression"
EE_SHARE_BADRECT, // "share: error evaluating from rect expression"
EE_SHARE_BADIMAGE, // "share: named image not found"
};

extern const char *MCexecutionerrors;

#endif
