/* gtk3_direct_stubs.cpp
 *
 * GTK2 → GTK3 migration: no-op replacements for the weak-stub initialise
 * functions that were previously generated by weak_stub_maker.pl for the
 * gdk / gobject / gtk / glib / pango / pangocairo / pangoft2 sections of
 * linux.stubs.  Those sections have been removed because we now link these
 * libraries directly (they ship with every GTK3 system) rather than
 * dlopen-ing them at runtime.
 *
 * The source files that call these functions have declarations like:
 *   extern "C" int initialise_weak_link_gtk();
 * so they must be defined with C linkage and return non-zero on "success".
 *
 * Also provides pango_layout_get_line_readonly_ptr, which lnxtext.cpp
 * accesses via an extern pointer rather than calling the function directly.
 */

#include <pango/pango.h>

extern "C"
{

int initialise_weak_link_gdk(void)       { return 1; }
int initialise_weak_link_gobject(void)   { return 1; }
int initialise_weak_link_gtk(void)       { return 1; }
int initialise_weak_link_glib(void)      { return 1; }
int initialise_weak_link_pango(void)     { return 1; }
int initialise_weak_link_pangocairo(void){ return 1; }
int initialise_weak_link_pangoft2(void)  { return 1; }

/* dsklnxmain.cpp calls this as "required" (void return, abort on failure).
 * Since glib is now directly linked and always available, this is a no-op. */
void initialise_required_weak_link_glib(void) { }

} // extern "C"

/* lnxtext.cpp uses this as an extern pointer so it can nil-check it.
 * Now that pango is directly linked the function is always present. */
PangoLayoutLine *(*pango_layout_get_line_readonly_ptr)(PangoLayout *, int) =
    pango_layout_get_line_readonly;
