#ifndef __MC_PARSE_ERRORS__
#define __MC_PARSE_ERRORS__
enum Parse_errors
{
PE_UNDEFINED=0,
PE_OBJECT_NAME, // "Object Name:"
PE_OBJECT_NOTLICENSED, // "set: license limit exceeded"
PE_ABS_BADPARAM, // "abs: bad parameter"
PE_ACCEPT_BADEXP, // "accept: bad expression"
PE_ACOS_BADPARAM, // "acos: bad parameter"
PE_ADD_BADDEST, // "add: bad destination"
PE_ADD_BADEXP, // "add: bad expression"
PE_ADD_NOTO, // "add: missing 'to'"
PE_ALIASREFERENCE_BADPARAM, // "aliasReference: bad expression"
PE_ANNUITY_BADPARAM, // "annuity: bad parameter"
PE_ANSWER_BADQUESTION, // "answer: bad question"
PE_ANSWER_BADRESPONSE, // "answer: bad response"
PE_ANSWER_BADTITLE, // "answer: bad title"
PE_ARRAYOP_BADARRAY, // "split: bad variable"
PE_ARRAYOP_NOWITH, // "split: missing 'with'"
PE_ARRAYOP_BADEXP, // "split: bad expression"
PE_ARROWKEY_BADEXP, // "arrowKey: bad direction expression"
PE_ASIN_BADPARAM, // "asin: bad parameter"
PE_ASK_BADQUESTION, // "ask: bad question"
PE_ASK_BADREPLY, // "ask: bad reply"
PE_ASK_BADTITLE, // "ask: bad title"
PE_ATAN2_BADPARAM, // "atan2: bad parameter"
PE_ATAN_BADPARAM, // "atan: bad parameter"
PE_AVERAGE_BADPARAM, // "average: bad parameter"
PE_BASE64DECODE_BADPARAM, // "base64Decode: bad parameter"
PE_BASE64ENCODE_BADPARAM, // "base64Encode: bad parameter"
PE_BASECONVERT_BADPARAM, // "baseConvert: bad parameter"
PE_BINARYD_BADPARAM, // "binaryDecode: bad expression"
PE_BINARYE_BADPARAM, // "binaryEncode: bad expression"
PE_CANCEL_BADEXP, // "cancel: bad message expression"
PE_CANCELNOTIFICATION_BADTAG, // "// cancelNotification: bad tag expression"
PE_CHARTONUM_BADPARAM, // "charToNum: bad parameter"
PE_CHOOSE_BADEXP, // "choose: bad expression"
PE_CHOOSE_NOTOKEN, // "choose: no tool specified"
PE_CHUNK_BADCHUNK, // "Chunk: token is not a chunk"
PE_CHUNK_BADDEST, // "Chunk: bad destination"
PE_CHUNK_BADEXP, // "Chunk: bad non-chunk expression"
PE_CHUNK_BADORDER, // "Chunk: bad chunk order (must be small to large)"
PE_CHUNK_BADPREP, // "Chunk: bad preposition"
PE_CHUNK_BADRANGE, // "Chunk: bad range"
PE_CHUNK_BADSTACKREF, // "Chunk: bad stack reference"
PE_CHUNK_NOCHUNK, // "Chunk: missing chunk"
PE_CHUNK_NOENDEXP, // "Chunk: bad expression"
PE_CHUNK_NOSTARTEXP, // "Chunk: bad range end expression"
PE_CHUNK_NOVARIABLE, // "Chunk: can't create a variable with that name (explicitVariables?)"
PE_CLICK_BADBUTTONEXP, // "click: bad \"button\" expression"
PE_CLICK_BADLOCATIONEXP, // "click: bad location expression"
PE_CLICK_NOAT, // "click: missing 'at'"
PE_CLONE_BADCHUNK, // "clone: bad name expression"
PE_CLONE_BADNAME, // "clone: bad target expression"
PE_CLOSE_BADEXP, // "close: bad stack expression"
PE_CLOSE_BADNAME, // "close: bad stack name"
PE_CLOSE_NOTYPE, // "close: no stack type"
PE_COMPACT_BADPARAM, // "compact: error in stack expression"
PE_COMPRESS_BADPARAM, // "compound: bad parameter"
PE_COMPOUND_BADPARAM, // "compress: bad parameter"
PE_CONSTANT_BADINIT, // "constant: error in value string"
PE_CONSTANT_NOINIT, // "constant: missing value string"
PE_CONVERT_BADAND, // "convert: 'and' in the wrong place"
PE_CONVERT_NOCONTAINER, // "convert: no container specified"
PE_CONVERT_NOFORMAT, // "convert: no format supplied"
PE_CONVERT_NOTFORMAT, // "convert: not a valid format"
PE_CONVERT_NOTO, // "convert: missing 'to'"
PE_COPY_BADDEST, // "copy: bad destination object expression"
PE_COS_BADPARAM, // "cos: bad parameter"
PE_CREATE_BADBGORCARD, // "create: bad background or card expression"
PE_CREATE_BADFILENAME, // "create: error in file name expression"
PE_CREATE_BADTYPE, // "create: can't create this type"
PE_CREATE_NOFILENAME, // "create: not an object type"
PE_CREATE_NONAME, // "create: no file name supplied"
PE_CREATE_NOTTYPE, // "create: no alias or directory name supplied"
PE_CREATE_NOTYPE, // "create: no object type"
PE_CREATE_NOWORKERNAME, // "// create worker: no worker name supplied"
PE_CROP_BADIMAGE, // "crop: bad image expression"
PE_CROP_BADRECT, // "crop: bad rect expression"
PE_DECOMPRESS_BADPARAM, // "decompress: bad parameter"
PE_DEFINE_BADOBJECT, // "define: bad object expression"
PE_DEFINE_INVALIDNAME, // "define: invalid property name"
PE_DELETE_BADFILEEXP, // "delete: bad file expression"
PE_DELETE_BADVAREXP, // "delete: bad variable expression"
PE_DISABLE_BADCHUNK, // "disable: no control specified"
PE_DIVIDE_BADDEST, // "divide: bad destination"
PE_DIVIDE_BADEXP, // "divide: bad expression"
PE_DIVIDE_NOBY, // "divide: missing 'by'"
PE_DO_BADEXP, // "do: bad expression"
PE_DO_BADLANG, // "do: bad language expression"
PE_DOMENU_BADEXP, // "doMenu: bad expression"
PE_DRAG_BADBUTTONEXP, // "drag: bad \"button\" expression"
PE_DRAG_BADENDLOCEXP, // "drag: bad end location expression"
PE_DRAG_BADSTARTLOCEXP, // "drag: bad start location expression"
PE_DRAG_NOFROM, // "drag: missing 'from'"
PE_DRAG_NOTO, // "drag: missing 'to'"
PE_DRIVERNAMES_BADPARAM, // "driverNames: bad in type expression"
PE_DRIVES_BADPARAM, // "drives: bad in type expression"
PE_EDIT_NOOF, // "edit: missing 'of'"
PE_EDIT_NOSCRIPT, // "edit: missing 'script'"
PE_EDIT_NOTARGET, // "edit: no object specified"
PE_ENCRYPT_BADPARAM, // "encrypt: bad parameter"
PE_EXIT_BADDEST, // "exit: bad destination expression"
PE_EXIT_NODEST, // "exit: no destination expression"
PE_EXP10_BADPARAM, // "exp10: bad parameter"
PE_EXP1_BADPARAM, // "exp1: bad parameter"
PE_EXP2_BADPARAM, // "exp2: bad parameter"
PE_EXPORT_BADFILENAME, // "export: bad file name"
PE_EXPORT_BADMASKNAME, // "export: bad mask file name"
PE_EXPORT_BADTYPE, // "export: bad image or image type expression"
PE_EXPORT_NOFILE, // "export: missing file name or container"
PE_EXPORT_NOMASK, // "export: missing 'mask'"
PE_EXPORT_NOTO, // "export: missing 'to'"
PE_EXPORT_NOTYPE, // "export: no image type specified"
PE_EXPRESSION_BADCHUNK, // "Expression: bad chunk"
PE_EXPRESSION_BADFUNCTION, // "Expression: bad function"
PE_EXPRESSION_BADPROPERTY, // "Expression: bad property"
PE_EXPRESSION_DOUBLEBINOP, // "Expression: double binary operator"
PE_EXPRESSION_NOBINOP, // "Expression: no binary operator"
PE_EXPRESSION_NOFACT, // "Expression: missing factor"
PE_EXPRESSION_NOLFACT, // "Expression: missing left operand to binary operator"
PE_EXPRESSION_NORPAR, // "Expression: missing ')'"
PE_EXPRESSION_NOTFACT, // "Expression: bad factor"
PE_EXPRESSION_NOTLITERAL, // "Expression: unquoted literal"
PE_EXPRESSION_WANTRPAR, // "Expression: missing ')' before factor"
PE_EXP_BADPARAM, // "exp: bad parameter"
PE_EXTENTS_BADPARAM, // "extents: bad parameter"
PE_FACTOR_BADPARAM, // "Function: bad parameter"
PE_FACTOR_NOOF, // "Function: missing 'of'"
PE_FACTOR_NOLPAREN, // "Function: missing '('"
PE_FACTOR_NORPAREN, // "Function: missing ')'"
PE_FACTOR_NOTSEP, // "Function: separator is not a ','"
PE_FILTER_BADDEST, // "filter: bad container"
PE_FILTER_BADEXP, // "filter: bad pattern expression"
PE_FILTER_NOWITH, // "filter: expected \"with\""
PE_FIND_BADFIELD, // "find: bad field expression"
PE_FIND_BADSTRING, // "find: bad string expression"
PE_FIND_NOSTRING, // "find: no string expression"
PE_FLIP_BADIMAGE, // "flip: bad image expression"
PE_FLIP_NODIR, // "flip: missing direction"
PE_FLUSHEVENTS_BADPARAM, // "flushEvents: bad event type expression"
PE_FOCUS_BADOBJECT, // "focus: bad object expression"
PE_FONTNAMES_BADPARAM, // "fontNames: bad type expression"
PE_FONTSIZES_BADPARAM, // "fontSizes: bad font name string"
PE_FONTSTYLES_BADPARAM, // "fontStyle: bad font name or size expression"
PE_FORMAT_BADPARAM, // "format: bad format string"
PE_FUNCTION_BADFORM, // "Function: bad form"
PE_FUNCTION_BADOBJECT, // "Function: bad object expression"
PE_FUNCTION_BADPARAMS, // "Function: bad parameter"
PE_FUNCTION_CANTMODIFY, // "Function: can't modify this function"
PE_GENERAL_CANTMODIFY, // "Function: missing function or property"
PE_GENERAL_NOMODIFY, // "Function: can't modify this token"
PE_GET_BADEXP, // "get: bad expression"
PE_GLOBAL_BADNAME, // "global: not a valid variable name"
PE_GLOBALLOC_BADPOINT, // "globalLoc: bad point expression"
PE_GO_BADCHUNKDEST, // "go: bad destination chunk"
PE_GO_BADCHUNKEXP, // "go: bad chunk expression"
PE_GO_BADCHUNKORDER, // "go: bad chunk order (must be small to large)"
PE_GO_BADCHUNKTYPE, // "go: bad destination type"
PE_GO_BADDESTEXP, // "go: bad destination expression"
PE_GO_BADDIRECT, // "go: bad direct destination "
PE_GO_BADPREP, // "go: bad window expression"
PE_GO_BADWINDOW, // "go: preposition in the wrong place"
PE_GO_DUPCHUNK, // "go: duplicate chunk"
PE_GO_NODEST, // "go: no destination specified"
PE_GO_NOID, // "go: missing id"
PE_GO_NOMODE, // "go: no window mode specified"
PE_GRAB_BADCHUNK, // "grab: bad object expression"
PE_HANDLERLIST_BADCHAR, // "Handler: bad character between handlers"
PE_HANDLERLIST_BADEOL, // "Handler: no end of line"
PE_HANDLERLIST_BADHANDLER, // "Handler: error in handler"
PE_HANDLER_BADCOMMAND, // "Handler: error in command"
PE_HANDLER_BADEND, // "Handler: end doesn't match handler name"
PE_HANDLER_BADLINE, // "Handler: unexpected end of line"
PE_HANDLER_BADNAME, // "Handler: bad handler name (may be reserved word)"
PE_HANDLER_BADPARAM, // "Handler: not a valid parameter name"
PE_HANDLER_BADPARAMEOL, // "Handler: unexpected end of line in parameters"
PE_HANDLER_BADVAR, // "Handler: error in variable or constant declaration"
PE_HANDLER_NOCOMMAND, // "Handler: bad command"
PE_HANDLER_NOEND, // "Handler: missing handler name after end"
PE_HANDLER_NONAME, // "Handler: no name specified"
PE_HANDLER_NOTCOMMAND, // "Handler: not a command"
PE_HASMEMORY_BADPARAM, // "hasMemory: bad amount expression"
PE_HIDE_BADEFFECT, // "hide: error in visual effect expression"
PE_HIDE_BADTARGET, // "hide: error in target object expression"
PE_HOSTADDRESS_BADSOCKET, // "hostAddress: error in socket expression"
PE_HOSTATON_BADADDRESS, // "hostAddressToName: error in address expression"
PE_HOSTNAME_BADNAME, // "hostName: error in name expression"
PE_HOSTNTOA_BADNAME, // "hostNameToAddress: error in name expression"
PE_IF_BADCONDITION, // "if: bad condition"
PE_IF_BADEOL, // "if: unexpected end of line"
PE_IF_BADSTATEMENT, // "if: error in command"
PE_IF_BADTYPE, // "if: garbage where a command should be"
PE_IF_NOTCOMMAND, // "if: not a command"
PE_IF_NOTHEN, // "if: missing 'then'"
PE_IF_WANTEDENDIF, // "if: missing 'end if'"
PE_IMPORT_BADFILENAME, // "import: bad file or display name"
PE_IMPORT_BADMASKNAME, // "import: bad mask file name"
PE_IMPORT_BADTYPE, // "import: bad image type"
PE_IMPORT_NOFILE, // "import: missing file or display name"
PE_IMPORT_NOFROM, // "import: missing 'from'"
PE_IMPORT_NOMASK, // "import: missing 'mask'"
PE_IMPORT_NOTYPE, // "import: no image type specified"
PE_INSERT_BADOBJECT, // "insert: bad object specification"
PE_INSERT_NOINTO, // "insert: expected 'into'"
PE_INSERT_NOPLACE, // "insert: missing 'script'"
PE_INSERT_NOSCRIPT, // "insert: expected 'front' or 'back'"
PE_INTERSECT_NOOBJECT, // "intersect: two objects are required"
PE_IS_BADAMONGTYPE, // "is: bad chunk type"
PE_IS_BADVALIDTYPE, // "is: bad validation type"
PE_IS_NORIGHT, // "is: missing validation type"
PE_IS_NOVALIDTYPE, // "is: no right operand"
PE_ISNUMBER_BADPARAM, // "isNumber: bad expression"
PE_ISOTOMAC_BADPARAM, // "isoToMac: bad source expression"
PE_KEYS_BADPARAM, // "keys: bad variable name"
PE_KILL_BADNAME, // "kill: bad process name"
PE_KILL_NOPROCESS, // "kill: no process"
PE_LAUNCH_BADAPPEXP, // "launch: error in application expression"
PE_LENGTH_BADPARAM, // "length: bad parameter"
PE_LN1_BADPARAM, // "ln: bad parameter"
PE_LN_BADPARAM, // "ln1: bad parameter"
PE_LOAD_BADURLEXP, // "load: error in url expression"
PE_LOAD_BADMESSAGEEXP, // "load: error in message expression"
PE_LOCAL_BADINIT, // "local: error in initialization string"
PE_LOCAL_BADNAME, // "local: not a valid variable or constant name"
PE_LOCAL_SHADOW, // "local: name shadows another variable or constant"
PE_LOCALLOC_BADPOINT, // "localLoc: bad point expression"
PE_LOCK_NOTARGET, // "lock: no target object specified"
PE_LOCK_NOTTARGET, // "lock: not a valid target object"
PE_LOG10_BADPARAM, // "log10: bad parameter"
PE_LOG2_BADPARAM, // "log2: bad parameter"
PE_LONGFILEPATH_BADPARAM, // "longFilePath: bad file expression"
PE_MACTOISO_BADPARAM, // "macToIso: bad source expression"
PE_MARK_BADFIELD, // "mark: bad 'field' expression"
PE_MARK_BADSTRING, // "mark: bad 'finding' string expression"
PE_MARK_BADWHEREEXP, // "mark: bad 'where' expression"
PE_MARK_NOBYORWHERE, // "mark: missing 'by' or 'where'"
PE_MARK_NOCARDS, // "mark: missing 'cards'"
PE_MARK_NOFINDING, // "mark: missing 'finding'"
PE_MARK_NOSTRING, // "mark: missing 'finding' string"
PE_MARK_NOTBYORWHERE, // "mark: expected 'by' or 'where'"
PE_MARK_NOTCARDS, // "mark: expected 'cards'"
PE_MATCH_BADPARAM, // "matchChunk: bad parameter"
PE_MATRIXMULT_BADPARAM, // "matrixMultiply: bad parameter"
PE_MAX_BADPARAM, // "max: bad parameter"
PE_MCISENDSTRING_BADPARAM, // "MCISendString: bad source expression"
PE_MD5DIGEST_BADPARAM, // "MD5digest: bad source expression"
PE_ME_THE, // "median: bad source expression"
PE_MEDIAN_BADPARAM, // "me: unexpected 'the'"
PE_MERGE_BADPARAM, // "merge: bad source expression"
PE_MIN_BADPARAM, // "min: bad parameter"
PE_MOUSE_BADPARAM, // "mouse: bad parameter"
PE_MOVE_BADOBJECT, // "move: bad object expression"
PE_MOVE_BADENDLOCEXP, // "move: bad end location expression"
PE_MOVE_BADSTARTLOCEXP, // "move: bad start location expression"
PE_MOVE_BADWITHOUT, // "move: expected 'messages' or 'waiting'"
PE_MOVE_NOTO, // "move: missing 'to'"
PE_MULTIPLY_BADDEST, // "multiply: bad destination"
PE_MULTIPLY_BADEXP, // "multiply: bad expression"
PE_MULTIPLY_NOBY, // "multiply: missing 'by'"
PE_NEXT_NOREPEAT, // "next: missing 'repeat'"
PE_NEXT_NOTREPEAT, // "next: token is not 'repeat'"
PE_NUMTOCHAR_BADPARAM, // "numToChar: bad parameter"
PE_OFFSET_BADPARAMS, // "offset: bad parameter"
PE_OPEN_BADMESSAGE, // "open: error in message expression"
PE_OPEN_BADMODE, // "open: bad mode"
PE_OPEN_BADNAME, // "open: bad file name"
PE_OPEN_BADTYPE, // "open: type must be 'file' or 'process'"
PE_OPEN_NOMODE, // "open: no mode specified"
PE_OPEN_NOTYPE, // "open: no type specified"
PE_PARAM_BADEXP, // "param: bad expression"
PE_PARAM_BADPARAM, // "param: bad parameter"
PE_PARSE_BADCHAR, // "Script: garbage character in script"
PE_PARSE_BADLIT, // "Script: missing '\"' after literal"
PE_PASS_NOMESSAGE, // "pass: mismatched or missing message to pass"
PE_PAUSE_BADCLIP, // "pause: bad clip name expression"
PE_PEERADDRESS_BADSOCKET, // "peerAddress: error in socket expression"
PE_PLACE_BADBACKGROUND, // "place: bad background expression"
PE_PLACE_BADCARD, // "place: bad card expression"
PE_PLAY_BADCLIP, // "play: bad clip name expression"
PE_PLAY_BADLOC, // "play: bad location expression"
PE_PLAY_BADOPTIONS, // "play: bad options expression"
PE_PLAY_BADTEMPO, // "play: bad tempo expression"
PE_PLAY_BADSTACK, // "play: bad stack expression"
PE_POP_BADCHUNK, // "pop: bad card expression"
PE_POP_BADPREP, // "pop: preposition in the wrong place"
PE_POP_NOCARD, // "pop: no card specified"
PE_POST_BADSOURCEEXP, // "post: bad source expression"
PE_POST_NOTO, // "post: missing 'to'"
PE_POST_BADDESTEXP, // "post: bad destination expression"
PE_PRINT_BADTARGET, // "print: bad target card"
PE_PRINT_BADFROMEXP, // "print: bad 'from' expression"
PE_PRINT_BADRECTEXP, // "print: bad rectangle expression"
PE_PRINT_NOTO, // "print: missing 'to'"
PE_PRINT_BADTOEXP, // "print: bad 'to' expression"
PE_PROPERTY_BADCHUNK, // "Properties: bad chunk expression"
PE_PROPERTY_BADINDEX, // "Properties: bad array index expression"
PE_PROPERTY_CANTMODIFY, // "Properties: can't modify this property"
PE_PROPERTY_MISSINGOFORIN, // "Properties: missing 'of'"
PE_PROPERTY_MISSINGTARGET, // "Properties: missing 'of' or 'in'"
PE_PROPERTY_NOPROP, // "Properties: no such property"
PE_PROPERTY_NOTAPROP, // "Properties: token is not a property"
PE_PROPERTY_NOTOF, // "Properties: expecting 'of'"
PE_PROPERTY_NOTOFORIN, // "Properties: expecting 'of' or 'in'"
PE_PUSH_BADEXP, // "push: bad expression"
PE_PUT_BADCHUNK, // "put: bad chunk"
PE_PUT_BADEXP, // "put: bad expression"
PE_PUT_BADPREP, // "put: preposition must be 'before', 'into' or 'after'"
PE_QUERYREGISTRY_BADPARAM, // "queryRegistry: bad parameter expression"
PE_RANDOM_BADPARAM, // "random: bad parameter"
PE_READ_BADAT, // "read: bad 'at' expression"
PE_READ_BADCOND, // "read: bad condition"
PE_READ_BADMESS, // "read: bad message expression"
PE_READ_BADNAME, // "read: bad file name expression"
PE_READ_BADTYPE, // "read: bad source type (should be 'file' or 'process')"
PE_READ_NOCOND, // "read: no termination condition specified"
PE_READ_NOFROM, // "read: missing 'from'"
PE_READ_NOTCOND, // "read: bad termination condition"
PE_READ_NOTYPE, // "read: missing source type ('file' or 'process')"
PE_RECORD_BADFILEEXP, // "record: missing 'file' or file name"
PE_REMOVE_BADOBJECT, // "remove: bad object expression"
PE_REMOVE_NOFROM, // "remove: expected 'from'"
PE_REMOVE_NOPLACE, // "remove: expected 'front' or 'back'"
PE_RENAME_BADEXP, // "rename: bad expression"
PE_REPEAT_BADCOMMAND, // "repeat: error in command"
PE_REPEAT_BADCOND, // "repeat: bad termination condition"
PE_REPEAT_BADCONDEOL, // "repeat: unexpected end of line in condition	"
PE_REPEAT_BADCONDTYPE, // "repeat: missing condition"
PE_REPEAT_BADFORMEOL, // "repeat: unexpected end of line"
PE_REPEAT_BADFORMTYPE, // "repeat: error in 'for' condition"
PE_REPEAT_BADSTATEMENT, // "repeat: garbage in repeat condition"
PE_REPEAT_BADTOKEN, // "repeat: not a command"
PE_REPEAT_BADWITHENDEXP, // "repeat: bad 'with' end expression"
PE_REPEAT_BADWITHSTARTEXP, // "repeat: bad 'with' start expression"
PE_REPEAT_BADWITHSTEPEXP, // "repeat: bad 'with' step expression"
PE_REPEAT_BADWITHVAR, // "repeat: bad 'with' variable"
PE_REPEAT_NODOWNTO, // "repeat: missing 'to' after 'down'"
PE_REPEAT_NOEQUALS, // "repeat: missing '='"
PE_REPEAT_NOOF, // "repeat: missing 'in'"
PE_REPEAT_NOTCOMMAND, // "repeat: garbage where a command should be"
PE_REPEAT_NOTEQUALS, // "repeat: expecting '='"
PE_REPEAT_NOTWITHTO, // "repeat: expecting 'to'"
PE_REPEAT_NOWITHTO, // "repeat: missing 'to'"
PE_REPEAT_NOWITHVAR, // "repeat: missing 'with' variable"
PE_REPEAT_WANTEDENDREPEAT, // "repeat: missing 'end repeat'"
PE_REPLACE_BADCONTAINER, // "replace: bad container expression"
PE_REPLACE_BADEXP, // "replace: bad expression"
PE_REPLACETEXT_BADPARAM, // "replaceText: bad parameter"
PE_REPLY_BADEXP, // "reply: error in message expression"
PE_REPLY_BADKEYWORD, // "reply: error in keyword expression"
PE_REQUEST_BADEXP, // "request: error in message expression"
PE_REQUEST_BADPROGRAM, // "request: error in program expression"
PE_REQUEST_NOTYPE, // "request: no 'type' expression"
PE_REQUEST_NOTTYPE, // "request: type must be class, ID, sender, returnID, or data"
PE_RESET_NOTYPE, // "reset: missing 'paint', 'cursors', or template object"
PE_RESOURCES_BADPARAM, // "getResources: bad parameter"
PE_RETURN_BADEXP, // "return: error in expression"
PE_ROTATE_BADIMAGE, // "rotate: error in image expression"
PE_ROTATE_BADANGLE, // "rotate: error in angle expression"
PE_ROUND_BADPARAM, // "round: bad parameter"
PE_SAVE_BADEXP, // "save: error in stack expression"
PE_SAVE_BADFILEEXP, // "save: error in file name expression"
PE_SEEK_BADMODE, // "seek: bad mode (should be 'to' or 'relative')"
PE_SEEK_BADNAME, // "seek: bad file name expression"
PE_SEEK_BADTYPE, // "seek: expected 'file'"
PE_SEEK_BADWHERE, // "seek: bad offset expression"
PE_SEEK_NOIN, // "seek: missing 'in'"
PE_SEEK_NOMODE, // "seek: no mode ('to' or 'relative')"
PE_SEEK_NOTYPE, // "seek: missing 'file'"
PE_SELECT_NOTARGET, // "select: missing target chunk"
PE_SELECT_NOOF, // "select: missing 'of'"
PE_SELECT_BADTARGET, // "select: bad target chunk"
PE_SELECTEDBUTTON_NOFAMILY, // "selectedButton: missing 'family'"
PE_SELECTEDBUTTON_NOOBJECT, // "selectedButton: bad card expression"
PE_SEND_BADEXP, // "send: bad message or expression"
PE_SEND_BADEVENTTYPE, // "send: bad event type expression"
PE_SEND_BADTARGET, // "send: bad target chunk or program expression"
PE_SHARE_BADDATA, // "// share: bad data expression"
PE_SHARE_BADRECT, // "// share: bad rect expression after 'from'"
PE_SET_BADEXP, // "set: error in expression"
PE_SET_NOPROP, // "set: no property specified"
PE_SET_NOTHE, // "set: missing 'the'"
PE_SET_NOTO, // "set: missing 'to'"
PE_SETREGISTRY_BADPARAM, // "setRegistry: bad parameter expression"
PE_SHELL_BADPARAM, // "shell: bad parameter"
PE_SHORTFILEPATH_BADPARAM, // "shortFilePath: bad file expression"
PE_SHOW_BADEFFECT, // "show: error visual effect expression"
PE_SHOW_BADLOCATION, // "show: error in location expression"
PE_SHOW_BADTARGET, // "show: error in object expression"
PE_SHOWNOTIFICATION_BADTITLE, // "// showNotification: bad title expression"
PE_SIN_BADPARAM, // "sin: bad parameter"
PE_SORT_BADEXPRESSION, // "sort: bad expression"
PE_SORT_BADTARGET, // "sort: error in object expression"
PE_SORT_NOTARGET, // "sort: no object specified"
PE_SPECIALFOLDERPATH_BADTYPE, // "specialFolderPath: bad type expression"
PE_SQRT_BADPARAM, // "sqrt: bad parameter"
PE_START_BADCHUNK, // "start: error in chunk expression"
PE_START_NOTTYPE, // "start: bad action (should be 'editing' or 'using')"
PE_START_NOTYPE, // "start: no action specified ('editing' or 'using')"
PE_STATEMENT_BADCHUNK, // "Commands: not a valid object expression"
PE_STATEMENT_BADINEXP, // "Commands: bad 'in' expression"
PE_STATEMENT_BADKEY, // "Commands: not a modifier key"
PE_STATEMENT_BADPARAM, // "Commands: bad parameter"
PE_STATEMENT_BADPARAMS, // "Commands: bad parameters"
PE_STATEMENT_BADSEP, // "Commands: missing ','"
PE_STATEMENT_NOKEY, // "Commands: missing modifier key "
PE_STATEMENT_NOTAND, // "Commands: expected 'and'"
PE_STATEMENT_NOTSEP, // "Commands: expected ','"
PE_STDDEV_BADPARAM, // "stdDev: bad parameters"
PE_STOP_BADCHUNK, // "stop: error in chunk expression"
PE_STOP_NOTTYPE, // "stop: bad action (must be editing, moving, playing, or using)"
PE_STOP_NOTYPE, // "stop: no action (must be editing, moving, playing, or using)"
PE_SUBTRACT_BADDEST, // "subtract: bad destination"
PE_SUBTRACT_BADEXP, // "subtract: bad expression"
PE_SUBTRACT_NOFROM, // "subtract: missing 'from'"
PE_SUBWINDOW_BADEXP, // "Stack: bad stack expression"
PE_SUM_BADPARAM, // "sum: bad parameter"
PE_SWITCH_BADCASECONDITION, // "switch: bad 'case' condition"
PE_SWITCH_BADCONDITION, // "switch: bad condition"
PE_SWITCH_BADSTATEMENT, // "switch: error in command"
PE_SWITCH_BADTYPE, // "switch: garbage where a command should be"
PE_SWITCH_NOTCOMMAND, // "switch: not a command"
PE_SWITCH_WANTEDENDSWITCH, // "switch: missing 'end switch'"
PE_TAN_BADPARAM, // "tan: bad parameter"
PE_THERE_BADFILE, // "Operators there: bad file expression"
PE_THERE_NOIS, // "Operators there: missing 'is'"
PE_THERE_NOOBJECT, // "Operators there: no object specified"
PE_THROW_BADERROR, // "throw: bad error expression"
PE_TOLOWER_BADPARAM, // "toLower: bad parameter"
PE_TOPSTACK_BADPARAM, // "topStack: bad parameter"
PE_TOUPPER_BADPARAM, // "toUpper: bad parameter"
PE_TRANSPOSE_BADPARAM, // "transpose: bad variable parameter"
PE_TRUNC_BADPARAM, // "trunc: bad parameter"
PE_TRY_BADSTATEMENT, // "try: error in command"
PE_TRY_BADTYPE, // "try: garbage where a command should be"
PE_TRY_NOTCOMMAND, // "try: not a command"
PE_TRY_WANTEDENDTRY, // "try: missing 'end try'"
PE_TYPE_BADEXP, // "type: bad string expression"
PE_UNGROUP_BADGROUP, // "ungroup: bad group expression"
PE_UNIDECODE_BADPARAM, // "uniDecode: bad parameter"
PE_UNIENCODE_BADPARAM, // "uniEncode: bad parameter"
PE_UNLOAD_BADURLEXP, // "unload: bad url expression"
PE_UNLOCK_BADEFFECT, // "unlock: not a visual effect"
PE_UNLOCK_NOTARGET, // "unlock: no type specified ('screen', 'recent' or 'messages')"
PE_UNLOCK_NOTTARGET, // "unlock: bad type specified ('screen', 'recent' or 'messages')"
PE_URLDECODE_BADPARAM, // "urlDecode: bad parameter"
PE_URLENCODE_BADPARAM, // "urlEncode: bad parameter"
PE_URLSTATUS_BADPARAM, // "urlStatus: bad url expression"
PE_VALUE_BADPARAM, // "value: bad parameter"
PE_VALUE_BADOBJECT, // "value: bad object expression"
PE_VARIABLE_BADINDEX, // "Array: bad index"
PE_VARIABLE_NORBRACE, // "Array: missing ']'"
PE_VISUAL_DUPDIRECTION, // "visual: double directions specified"
PE_VISUAL_DUPVISUAL, // "visual: double effect specified"
PE_VISUAL_NOTID, // "visual: expected visual name"
PE_VISUAL_NOTOKEN, // "visual: missing visual name"
PE_VISUAL_NOTVISUAL, // "visual: not a visual name"
PE_WAIT_BADCOND, // "wait: error in condition expression"
PE_WAIT_NODURATION, // "wait: no duration expression"
PE_WITHIN_NOOBJECT, // "within: bad object expression"
PE_WITHIN_BADPOINT, // "within: bad point expression"
PE_WRITE_BADAT, // "write: bad 'at' expression"
PE_WRITE_BADEXP, // "write: error in source expression"
PE_WRITE_BADNAME, // "write: bad file name"
PE_WRITE_BADTYPE, // "write: bad destination (should be 'file or process')"
PE_WRITE_NOTO, // "write: missing 'to'"
PE_WRITE_NOTYPE, // "write: no destination (should be 'file or process')"
PE_ENCRYPTION_NOSOURCE, // "encrypt/decrypt: source container expected, but not supplied"
PE_ENCRYPTION_NOCIPHER, // "encrypt/decrypt: cipher name expected, but not supplied"
PE_ENCRYPTION_NOKEY, // "encrypt/decrypt: key expected, but not supplied"
PE_ENCRYPTION_NOBIT, // "encrypt/decrypt: 'at' clause supplied, but trailing 'bit' missing"
PE_ENCRYPTION_BADSOURCE, // "encrypt/decrypt: error parsing source container"
PE_ENCRYPTION_BADCIPHER, // "encrypt/decrypt: error parsing cipher expression"
PE_ENCRYPTION_BADKEY, // "encrypt/decrypt: error parsing key expression"
PE_ENCRYPTION_BADSALT, // "encrypt/decrypt: error parsing salt expression"
PE_ENCRYPTION_BADIV, // "encrypt/decrypt: error parsing IV expression"
PE_ENCRYPTION_BADBIT, // "encrypt/decrypt: error parsing bit expression"
PE_ENCRYPTION_BADPARAM, // "encrypt/decrypt: invalid clause supplied in this context"
PE_VISUAL_NOPARAM, // "visual: no parameter"
PE_VISUAL_BADPARAM, // "visual: bad parameter"
PE_PRIVATE_BADPASS, // "private: pass not valid in context"
PE_BEGINSENDS_NOWITH, // "begins/ends with: bad parameter"
PE_NUMTOBYTE_BADPARAM, // "numtobyte: bad parameter"
PE_BYTETONUM_BADPARAM, // "bytetonum: bad parameter"
PE_ARRAYDECODE_BADPARAM, // "arraydecode: bad parameter"
PE_ARRAYENCODE_BADPARAM, // "arrayencode: bad parameter"
PE_DISPATCH_BADMESSAGE, // "dispatch: bad message"
PE_DISPATCH_BADPARAMS, // "dispatch: bad parameters"
PE_DISPATCH_BADTARGET, // "dispatch: bad target"
PE_DISPATCH_BADWORKERNAME, // "// dispatch: bad worker name expression"
PE_DO_BADENV, // "do: unknown target environment"
PE_EXPORT_BADPALETTE, // "export: bad palette type"
PE_OPENPRINTING_NODST, // "printing: missing destination"
PE_OPENPRINTING_NOFILENAME, // "printing: missing filename"
PE_OPENPRINTING_BADOPTIONS, // "printing: bad options expression"
PE_PRINTANCHOR_BADNAMEEXP, // "print: bad anchor name expression"
PE_PRINTANCHOR_NOATEXP, // "print: no anchor location expression"
PE_PRINTANCHOR_BADTOEXP, // "print: bad anchor target expression"
PE_PRINTLINK_NOTOEXP, // "print: no link location expression"
PE_PRINTLINK_BADTOEXP, // "print: bad link target expression"
PE_PRINTLINK_NOAREAEXP, // "print: no link area expression"
PE_PRINTLINK_BADAREAEXP, // "print: bad link area expression"
PE_HANDLER_DUPPARAM, // "Handler: repeated parameter name"
PE_INTERNAL_BADVERB, // ""
PE_INTERNAL_BADNOUN, // ""
PE_INTERNAL_BADEOS, // ""
PE_RANDOMBYTES_BADPARAM, // "randomBytes: bad parameter expression"
PE_SHA1DIGEST_BADPARAM, // "sha1Digest: bad parameter expression"
PE_PRINTBOOKMARK_BADTITLEEXP, // "print: bad bookmark title expression"
PE_PRINTBOOKMARK_NOLEVEL, // "print: no bookmark level expression"
PE_PRINTBOOKMARK_BADLEVELEXP, // "print: bad bookmark level expression"
PE_PRINTBOOKMARK_BADATEXP, // "print: bad bookmark location expression"
PE_PRINTBOOKMARK_NOBOOKMARK, // "print: no bookmark expression"
PE_PRINTBOOKMARK_BADINITIALEXP, // "print: bad bookmark initial state expression"
PE_SCRIPT_BADHANDLER, // "script: bad handler declaration"
PE_SCRIPT_BADHANDLERTYPE, // "script: illegal handler type in global script"
PE_SCRIPT_BADVAR, // "script: bad variable declaration"
PE_SCRIPT_BADSTATEMENT, // "script: bad statement"
PE_SCRIPT_NOTSTATEMENT, // "script: not a statment"
PE_SCRIPT_BADCOMMAND, // "script: bad command"
PE_SCRIPT_NOTCOMMAND, // "script: not a command"
PE_SCRIPT_BADEOL, // "script: unexpected eol"
PE_SCRIPT_BADCHAR, // "script: illegal character"
PE_INCLUDE_BADFILENAME, // "include: bad filename expression"
PE_REQUIRE_BADFILENAME, // "require: bad filename expression"
PE_SCRIPT_BADECHO, // "echo: malformed implicit put"
PE_LOCK_BADRECT, // "lock: bad rect expression"
PE_LOCK_NORECT, // "lock: missing 'rect' keyword"
PE_RELAYER_BADCONTROL, // "relayer: bad source control"
PE_RELAYER_BADRELATION, // "relayer: invalid relation."
PE_RELAYER_BADTARGET, // "relayer: bad target control"
PE_CONTROLATLOC_BADPARAM, // "controlAtLoc: bad location expression"
PE_ARRAYOP_BADFORM, // "split/combine: bad form clause"
PE_UUID_BADPARAM, // "uuid: bad parameter list"
PE_AVGDEV_BADPARAM, // "avgDev: bad parameters"
PE_GEO_MEAN_BADPARAM, // "geometricMean: bad parameters"
PE_HAR_MEAN_BADPARAM, // "harmonicMean: bad parameters"
PE_POP_STDDEV_BADPARAM, // "pStdDev: bad parameters"
PE_POP_VARIANCE_BADPARAM, // "pVariance: bad parameters"
PE_VARIANCE_BADPARAM, // "variance: bad parameters"
PE_MEASURE_TEXT_NOOBJECT, // "measureText: no object"
PE_MEASURE_TEXT_BADTEXT, // "measureText: bad text parameter"
PE_MEASURE_TEXT_BADMODE, // "measureText: bad mode parameter"
PE_RESOLVE_BADIMAGE, // "resolve image: bad image reference"
PE_RESOLVE_BADOBJECT, // "resolve image: bad object reference"
PE_EDIT_NOAT, // "edit script: no at expression"
PE_ASSERT_BADTYPE, // "assert: bad type"
PE_ASSERT_BADEXPR, // "assert: bad expression"
PE_SECURE_NOSOCKET, // "secure: missing 'socket'"
PE_SECURE_BADNAME, // "secure: bad socket name"
PE_SECURE_BADMESSAGE, // "secure: expected 'verification'"
PE_TEXTDECODE_BADPARAM, // "textDecode: bad parameters"
PE_TEXTENCODE_BADPARAM, // "textEncode: bad parameters"
PE_NORMALIZETEXT_BADPARAM, // "normalizeText: bad parameters"
PE_CODEPOINTPROPERTY_BADPARAM, // "codepointProperty: bad parameters"
PE_OPEN_BADENCODING, // "open: bad encoding parameter"
PE_OPEN_BADBINARYENCODING, // "open: no encoding when opening in binary mode"
PE_SECURE_BADHOST, // "secure: bad host name"
PE_SECURE_NOHOST, // "secure: expected 'host'"
PE_OPEN_BADHOST, // "open: bad host name"
PE_OPEN_NOHOST, // "open: expected 'host'"
PE_BIDIDIRECTION_BADPARAM, // "bidiDirection: bad parameters"
PE_FLOOR_BADPARAM, // "floor: error in source expression"
PE_CEIL_BADPARAM, // "ceil: error in source expression"
PE_GLOBAL_SHADOW, // "global: shadowing a local variable"
PE_LOAD_BADEXTENSION, // "load: error in extension expression"
PE_LOAD_NORESOURCE, // "load: expected 'resource'"
PE_LOAD_NOPATH, // "load: expected 'path'"
PE_LOAD_BADRESOURCEPATH, // "load: error in resource path expression"
PE_LOAD_NOFILE, // "load: missing file or display name"
PE_LOAD_NOFROM, // "load: missing 'from'"
PE_ISSTRICTLY_NOAN, // "is strictly: missing 'an' or 'a'"
PE_ISSTRICTLY_NOSTRING, // "is strictly: missing 'string'"
PE_ISSTRICTLY_NOTYPE, // "is strictly: missing type"
PE_IMPORT_NOARRAY, // "import: no array expression"
PE_EXPORT_NOARRAY, // "export: no array expression"
PE_GO_BADWIDGETEXP, // "go: error in widget expression"
PE_LAUNCH_BADWIDGETEXP, // "launch: error in widget expression"
PE_SAVE_BADFORMATEXP, // "save: error in format expression"
PE_REPLACE_NOSTYLES, // "replace: missing 'styles'"
PE_REVERT_BADSTACK, // "revert: bad stack expression"
PE_VECTORDOT_BADPARAM, // "vectordot: bad parameter"
PE_RETURN_BADFORMINCONTEXT, // "return: form not allowed in handler type"
PE_RETURN_BADFOR, // "return: form not allowed in handler type"
PE_FILES_BADPARAM, // "files: bad folder expression"
PE_FOLDERS_BADPARAM, // "folders: bad folder expression"
PE_OPEN_NOFROM, // "open: expected 'from' address"
PE_MESSAGEDIGEST_BADPARAM, // "messageDigest: bad parameters"
PE_ARRAYOP_NODIFFERENCE, // "setop: missing 'difference'"
PE_ARRAYOP_BADRECURSIVE, // "setop: 'recursive' only makes sense for union or intersect"
PE_ARRAYOP_DSTNOTCONTAINER, // "setop: destination is not a container (did you mean to use 'into'?)"
PE_SEND_SCRIPTINTIME, // "send: can't send script in time"
PE_FONTLANGUAGE_BADPARAM, // "fontLanguage: bad type expression"
PE_OUTOFMEMORY, // "out of memory"
PE_MATCHES_NOMODE, // "matches: missing match mode 'regex' or 'wildcard'"
PE_IFF_BADPARAM, // "iff: requires exactly 3 parameters"
PE_STORECREDENTIAL_BADPARAM, // "storeCredential: bad parameter expression"
PE_RETRIEVECREDENTIAL_BADPARAM, // "retrieveCredential: bad parameter expression"
PE_DELETECREDENTIAL_BADPARAM, // "deleteCredential: bad parameter expression"
};

extern const char *MCparsingerrors;

#endif
